// =============================================================================
// Draft Parser Utilities
// =============================================================================

export interface ParsedDraft {
  name: string;
  timestamp: string;
  status: string;
  sections: {
    qian?: string;
    kun?: string;
    zhen?: string;
    xun?: string;
    kan?: string;
    li?: string;
    gen?: string;
    dui?: string;
  };
  notes?: string;
}

export function parseDraft(content: string): ParsedDraft | null {
  try {
    const lines = content.split("\n");
    let name = "";
    let timestamp = "";
    let status = "";
    const sections: ParsedDraft["sections"] = {};
    let currentSection: keyof ParsedDraft["sections"] | "notes" | "" = "";
    let notes = "";

    for (const line of lines) {
      // Parse header
      if (line.startsWith("Generated by:")) {
        // skip
      } else if (line.startsWith("Timestamp:")) {
        timestamp = line.replace("Timestamp:", "").trim();
      } else if (line.startsWith("Status:")) {
        status = line.replace("Status:", "").trim();
      } else if (line.startsWith("# Design Draft:")) {
        name = line.replace("# Design Draft:", "").trim();
      }
      // Parse sections
      else if (line.startsWith("## ☰ Qian")) {
        currentSection = "qian";
      } else if (line.startsWith("## ☷ Kun")) {
        currentSection = "kun";
      } else if (line.startsWith("## ☳ Zhen")) {
        currentSection = "zhen";
      } else if (line.startsWith("## ☴ Xun")) {
        currentSection = "xun";
      } else if (line.startsWith("## ☵ Kan")) {
        currentSection = "kan";
      } else if (line.startsWith("## ☲ Li")) {
        currentSection = "li";
      } else if (line.startsWith("## ☶ Gen")) {
        currentSection = "gen";
      } else if (line.startsWith("## ☱ Dui")) {
        currentSection = "dui";
      } else if (line.startsWith("## Notes")) {
        currentSection = "notes";
      } else if (currentSection && line.trim()) {
        if (currentSection === "notes") {
          notes += line + "\n";
        } else {
          sections[currentSection] = (sections[currentSection] || "") + line + "\n";
        }
      }
    }

    return { name, timestamp, status, sections, notes: notes.trim() };
  } catch {
    return null;
  }
}

export function isDraftComplete(draft: ParsedDraft): boolean {
  const sectionCount = Object.values(draft.sections).filter((s) => s && s.trim().length > 10).length;
  return sectionCount >= 5; // At least 5 sections filled
}