/**
 * Unit Tests for Draft Generator
 * Tests MDD (Multi-Dimensional Design) draft generation
 */
import { describe, it, expect } from "bun:test";
import { generateMinimalDraft, generateDraft, type DraftConfig } from "@/utils/draft-generator";

describe("Draft Generator", () => {
  describe("generateMinimalDraft", () => {
    it("should generate draft with name", () => {
      const draft = generateMinimalDraft("test-project", "Build authentication");
      expect(draft).toContain("test-project");
    });

    it("should generate draft with intent", () => {
      const intent = "Build user authentication with JWT";
      const draft = generateMinimalDraft("auth-api", intent);
      expect(draft).toContain(intent);
    });

    it("should include MDD structure", () => {
      const draft = generateMinimalDraft("test", "Test request");
      expect(draft).toContain("## Overview");
      expect(draft).toContain("Business Plane");
      expect(draft).toContain("Data Plane");
    });

    it("should include all 7 MDD planes", () => {
      const draft = generateMinimalDraft("test", "Test");
      expect(draft).toContain("Business Plane");
      expect(draft).toContain("Data Plane");
      expect(draft).toContain("Control Plane");
      expect(draft).toContain("Foundation Plane");
      expect(draft).toContain("Observation Plane");
      expect(draft).toContain("Security Plane");
      expect(draft).toContain("Evolution Plane");
    });

    it("should include MDD Plane Analysis section", () => {
      const draft = generateMinimalDraft("test", "Test");
      expect(draft).toContain("MDD Plane Analysis");
    });

    it("should include Cross-Plane Dependencies section", () => {
      const draft = generateMinimalDraft("test", "Test");
      expect(draft).toContain("Cross-Plane Dependencies");
    });

    it("should include Key Design Decisions section", () => {
      const draft = generateMinimalDraft("test", "Test");
      expect(draft).toContain("Key Design Decisions");
    });

    it("should include Open Questions section", () => {
      const draft = generateMinimalDraft("test", "Test");
      expect(draft).toContain("Open Questions");
    });

    it("should include Notes section", () => {
      const draft = generateMinimalDraft("test", "Test");
      expect(draft).toContain("## Notes");
    });

    it("should include timestamp", () => {
      const draft = generateMinimalDraft("test", "Test");
      expect(draft).toContain("Timestamp:");
    });

    it("should include Generated by attribution", () => {
      const draft = generateMinimalDraft("test", "Test");
      expect(draft).toContain("Generated by");
    });
  });

  describe("generateDraft", () => {
    it("should generate draft from config", () => {
      const config: DraftConfig = {
        name: "auth-system",
        request: "Build authentication system",
        intent: "Secure user authentication with JWT",
        business: {
          process: ["User registration", "User login", "Password reset"],
          rules: ["Password must be 8+ characters", "Email must be verified"],
        },
      };
      
      const draft = generateDraft(config);
      expect(draft).toContain("auth-system");
      expect(draft).toContain("Secure user authentication");
    });

    it("should include business process items", () => {
      const config: DraftConfig = {
        name: "test",
        request: "Test",
        business: { process: ["Step 1", "Step 2"] },
      };
      
      const draft = generateDraft(config);
      expect(draft).toContain("Step 1");
      expect(draft).toContain("Step 2");
    });

    it("should include business rules items", () => {
      const config: DraftConfig = {
        name: "test",
        request: "Test",
        business: { rules: ["Rule 1", "Rule 2"] },
      };
      
      const draft = generateDraft(config);
      expect(draft).toContain("Rule 1");
      expect(draft).toContain("Rule 2");
    });

    it("should include data logic items", () => {
      const config: DraftConfig = {
        name: "test",
        request: "Test",
        data: { logic: ["JWT generation", "Password hashing"] },
      };
      
      const draft = generateDraft(config);
      expect(draft).toContain("JWT generation");
    });

    it("should include data state items", () => {
      const config: DraftConfig = {
        name: "test",
        request: "Test",
        data: { state: ["User session", "Token storage"] },
      };
      
      const draft = generateDraft(config);
      expect(draft).toContain("User session");
    });

    it("should handle empty config gracefully", () => {
      const config: DraftConfig = {
        name: "minimal",
        request: "Minimal draft",
      };
      
      const draft = generateDraft(config);
      expect(draft).toContain("minimal");
      expect(draft).toContain("Minimal draft");
    });

    it("should use default placeholders for missing fields", () => {
      const config: DraftConfig = {
        name: "test",
        request: "Test",
      };
      
      const draft = generateDraft(config);
      expect(draft).toContain("Business Plane");
      expect(draft).toContain("Data Plane");
    });
  });

  describe("MDD Planes", () => {
    it("should have 7 MDD planes", () => {
      const planes = [
        "Business",
        "Data",
        "Control",
        "Foundation",
        "Observation",
        "Security",
        "Evolution",
      ];
      expect(planes.length).toBe(7);
    });

    it("should have two elements per plane", () => {
      const planeElements = {
        Business: ["Process", "Rules"],
        Data: ["Logic", "State"],
        Control: ["Strategy", "Distribution"],
        Foundation: ["Resource", "Abstraction"],
        Observation: ["Data", "Analysis"],
        Security: ["Identity", "Permissions"],
        Evolution: ["Time", "Change"],
      };
      
      Object.values(planeElements).forEach(elements => {
        expect(elements.length).toBe(2);
      });
    });
  });
});

describe("DraftConfig", () => {
  it("should require name and request", () => {
    const config: DraftConfig = {
      name: "test",
      request: "Test request",
    };
    expect(config.name).toBe("test");
    expect(config.request).toBe("Test request");
  });

  it("should have optional fields", () => {
    const config: DraftConfig = {
      name: "test",
      request: "Test",
      intent: "Test intent",
      notes: "Test notes",
    };
    expect(config.intent).toBe("Test intent");
    expect(config.notes).toBe("Test notes");
  });
});

describe("Calculator/Math Requests", () => {
  const calculatorRequest = "Create a simple calculator function that supports basic arithmetic operations: addition, subtraction, multiplication, and division.";

  it("should generate valid MDD structure for calculator requests", () => {
    const draft = generateMinimalDraft("simple-calculator", calculatorRequest);
    
    // generateMinimalDraft produces MDD structure (not calculator-specific content)
    // The new generateRichDraft with project analysis will produce calculator-specific content
    expect(draft).toContain("System Design: simple-calculator");
    expect(draft).toContain("MDD Plane Analysis");
    expect(draft).toContain("Business Plane");
    expect(draft).toContain("Foundation Plane");
  });

  it("should include generic MDD planes", () => {
    const draft = generateMinimalDraft("simple-calculator", calculatorRequest);
    
    // Should have all 7 MDD planes
    expect(draft).toContain("1. Business Plane");
    expect(draft).toContain("2. Data Plane");
    expect(draft).toContain("3. Control Plane");
    expect(draft).toContain("4. Foundation Plane");
    expect(draft).toContain("5. Observation Plane");
    expect(draft).toContain("6. Security Plane");
    expect(draft).toContain("7. Evolution Plane");
  });

  it("should handle error cases gracefully", () => {
    const draft = generateMinimalDraft("simple-calculator", calculatorRequest);
    
    // Should generate valid MDD structure
    expect(draft).toContain("System Design:");
    expect(draft).toContain("MDD Plane Analysis");
  });

  it("should describe the function interface in Foundation Plane", () => {
    const draft = generateMinimalDraft("simple-calculator", calculatorRequest);
    
    // Should describe the public interface
    expect(draft).toContain("Abstraction");
    expect(draft.toLowerCase()).toMatch(/function|method|interface|api/);
  });

  it("should include data planes in MDD structure", () => {
    const draft = generateMinimalDraft("simple-calculator", calculatorRequest);
    
    // Should have Foundation and Data planes
    expect(draft).toContain("Foundation Plane");
    expect(draft).toContain("Data Plane");
  });

  it("should include TypeScript interface in Data Plane", () => {
    const draft = generateMinimalDraft("simple-calculator", calculatorRequest);
    
    // Should have Data Plane with logic
    expect(draft).toContain("Data Plane");
    expect(draft).toContain("Logic");
  });

  it("should include Control Plane with strategy", () => {
    const draft = generateMinimalDraft("simple-calculator", calculatorRequest);
    
    // Should have Control Plane for decision flow
    expect(draft).toContain("Control Plane");
    expect(draft).toContain("Strategy");
  });

  it("should include Foundation Plane with abstraction", () => {
    const draft = generateMinimalDraft("simple-calculator", calculatorRequest);
    
    // Should have Foundation Plane for API contracts
    expect(draft).toContain("Foundation Plane");
    expect(draft).toContain("Abstraction");
  });

  it("should include Evolution Plane for timeline", () => {
    const draft = generateMinimalDraft("simple-calculator", calculatorRequest);
    
    // Should have Evolution Plane for feature timeline
    expect(draft).toContain("Evolution Plane");
    expect(draft).toContain("Time");
  });
});

describe("Mathematical function requests", () => {
  it("should generate valid MDD structure for math function requests", () => {
    const mathRequest = "Create a math utility module for scientific calculations";
    const draft = generateMinimalDraft("math-utils", mathRequest);
    
    // Should generate valid MDD structure
    expect(draft).toContain("System Design: math-utils");
    expect(draft).toContain("MDD Plane Analysis");
    expect(draft).toContain("Business Plane");
  });
});

describe("Arithmetic operation requests", () => {
  it("should generate MDD structure for arithmetic requests", () => {
    const arithmeticRequest = "Implement arithmetic operations for financial calculations";
    const draft = generateMinimalDraft("arithmetic-ops", arithmeticRequest);
    
    // Should generate valid MDD structure
    expect(draft).toContain("System Design: arithmetic-ops");
    expect(draft).toContain("MDD Plane Analysis");
    expect(draft).toContain("Business Plane");
  });
});
