/**
 * Draft Generator - Creates MDD (Multi-Dimensional Design) drafts
 * Now supports context-aware generation from project analysis
 */

import type { ProjectContext } from "./analyzer/index.js";

export interface Scenario {
  name: string;
  given: string;
  when: string;
  then: string;
  but?: string;
}

export interface KeyAlternative {
  option: string;
  pros: string;
  cons: string;
}

export interface KeyDecision {
  id: string;            // e.g. "KD-1", "KD-2"
  decision: string;      // one-line summary of the choice
  context: string;       // what situation forces this decision
  alternatives: KeyAlternative[];
  rationale: string;     // why this option over others
  enforcedBy: string;    // code review | lint | test | convention | type check
}

export interface DraftConfig {
  name: string;
  request: string;
  intent?: string;
  // SSD-style scenarios (Given/When/Then) — drive TDD Red phase deterministically
  scenarios?: Scenario[];
  // MDD Planes
  business?: {
    process?: string[];
    rules?: string[];
  };
  data?: {
    logic?: string[];
    state?: string[];
  };
  control?: {
    strategy?: string[];
    distribution?: string[];
  };
  foundation?: {
    resource?: string[];
    abstraction?: string[];
  };
  observation?: {
    data?: string[];
    analysis?: string[];
  };
  security?: {
    identity?: string[];
    permissions?: string[];
  };
  evolution?: {
    time?: string[];
    change?: string[];
  };
  crossPlaneDependencies?: string[];
  // SSD-style key decisions — force consideration of alternatives before commit
  keyDecisions?: KeyDecision[];
  openQuestions?: string[];
  notes?: string;
}

const DRAFT_TEMPLATE = `# System Design: {name}

## Overview
{intent}

---

## Scenarios

> Given/When/Then specifications — each scenario maps 1:1 to a TDD Red phase in LuBan.
> Cover: **normal path**, **error path**, and at least one **edge case**.

{scenarios}

---

## MDD Plane Analysis

### 1. Business Plane: Process × Rules
**Focus**: Business value delivery

**Process**
{process}

**Rules**
{rules}

---

### 2. Data Plane: Logic × State
**Focus**: Data processing and state management

**Logic**
{logic}

**State**
{state}

---

### 3. Control Plane: Strategy × Distribution
**Focus**: Decision making and execution

**Strategy**
{strategy}

**Distribution**
{distribution}

---

### 4. Foundation Plane: Resource × Abstraction
**Focus**: Infrastructure and encapsulation

**Resource**
{resource}

**Abstraction**
{abstraction}

---

### 5. Observation Plane: Data × Analysis
**Focus**: Monitoring and insights

**Data**
{obsData}

**Analysis**
{analysis}

---

### 6. Security Plane: Identity × Permissions
**Focus**: Authentication and authorization

**Identity**
{identity}

**Permissions**
{permissions}

---

### 7. Evolution Plane: Time × Change
**Focus**: System evolution and versioning

**Time**
{time}

**Change**
{change}

---

## Cross-Plane Dependencies

{crossPlaneDeps}

---

## Key Design Decisions

> Each decision records **Context → Decision → Alternatives → Rationale → Enforced by**.
> Forces consideration of alternatives before commitment.

{keyDecisions}

---

## Open Questions

{openQuestions}

---

## Notes

{notes}

---

*Generated by Fuxi (伏羲) - Multi-Dimensional Design*
*Timestamp: {timestamp}*
`;

export function generateDraft(config: DraftConfig): string {
  const timestamp = new Date().toISOString();

  const formatList = (items?: string[]) => {
    if (!items || items.length === 0) return "- None specified";
    return items.map(item => `- ${item}`).join("\n");
  };

  const formatScenarios = (scenarios?: Scenario[]): string => {
    if (!scenarios || scenarios.length === 0) {
      return "_No scenarios defined yet. Add Given/When/Then cases to drive TDD._";
    }
    return scenarios
      .map(s => {
        let block = `### Scenario: ${s.name}\n`;
        block += `**Given** ${s.given}\n`;
        block += `**When** ${s.when}\n`;
        block += `**Then** ${s.then}`;
        if (s.but) block += `\n**But** ${s.but}`;
        return block;
      })
      .join("\n\n");
  };

  const formatKeyDecisions = (decisions?: KeyDecision[]): string => {
    if (!decisions || decisions.length === 0) {
      return "_No key decisions recorded yet. Add KD-1, KD-2, ... to commit to specific choices._";
    }
    return decisions
      .map(kd => {
        let block = `### ${kd.id}: ${kd.decision}\n`;
        block += `**Context**: ${kd.context}\n`;
        block += `**Decision**: ${kd.decision}\n`;
        if (kd.alternatives && kd.alternatives.length > 0) {
          block += `**Alternatives**:\n`;
          block += `| Option | Pros | Cons |\n`;
          block += `| --- | --- | --- |\n`;
          for (const alt of kd.alternatives) {
            block += `| ${alt.option} | ${alt.pros} | ${alt.cons} |\n`;
          }
        }
        block += `**Rationale**: ${kd.rationale}\n`;
        block += `**Enforced by**: ${kd.enforcedBy}`;
        return block;
      })
      .join("\n\n");
  };

  return DRAFT_TEMPLATE
    .replace("{name}", config.name)
    .replace("{timestamp}", timestamp)
    .replace("{intent}", config.intent || config.request)
    .replace("{scenarios}", formatScenarios(config.scenarios))
    // Business Plane
    .replace("{process}", formatList(config.business?.process))
    .replace("{rules}", formatList(config.business?.rules))
    // Data Plane
    .replace("{logic}", formatList(config.data?.logic))
    .replace("{state}", formatList(config.data?.state))
    // Control Plane
    .replace("{strategy}", formatList(config.control?.strategy))
    .replace("{distribution}", formatList(config.control?.distribution))
    // Foundation Plane
    .replace("{resource}", formatList(config.foundation?.resource))
    .replace("{abstraction}", formatList(config.foundation?.abstraction))
    // Observation Plane
    .replace("{obsData}", formatList(config.observation?.data))
    .replace("{analysis}", formatList(config.observation?.analysis))
    // Security Plane
    .replace("{identity}", formatList(config.security?.identity))
    .replace("{permissions}", formatList(config.security?.permissions))
    // Evolution Plane
    .replace("{time}", formatList(config.evolution?.time))
    .replace("{change}", formatList(config.evolution?.change))
    // Cross-cutting
    .replace("{crossPlaneDeps}", formatList(config.crossPlaneDependencies))
    .replace("{keyDecisions}", formatKeyDecisions(config.keyDecisions))
    .replace("{openQuestions}", formatList(config.openQuestions))
    .replace("{notes}", config.notes || "- Add notes here");
}

/**
 * Generate rich draft from project context
 * This is the NEW deep analysis version of generateMinimalDraft
 */
export function generateRichDraft(projectContext: ProjectContext, request: string): string {
  const lowerRequest = request.toLowerCase();
  
  // Analyze request type to customize plane content
  const requestType = analyzeRequestType(lowerRequest);
  
  // Generate plane content based on project context
  const businessPlane = generateBusinessPlane(projectContext, request, requestType);
  const dataPlane = generateDataPlane(projectContext, request, requestType);
  const controlPlane = generateControlPlane(projectContext, request, requestType);
  const foundationPlane = generateFoundationPlane(projectContext, request, requestType);
  const observationPlane = generateObservationPlane(projectContext, request, requestType);
  const securityPlane = generateSecurityPlane(projectContext, request, requestType);
  const evolutionPlane = generateEvolutionPlane(projectContext, request, requestType);

  // Generate starter scenarios (Given/When/Then) — TDD Red-phase input
  const scenarios = generateScenarios(projectContext, request, requestType);

  return generateDraft({
    name: projectContext.projectName,
    request,
    intent: `${requestType.description}\n\n**Project**: ${projectContext.projectName}\n**Language**: ${projectContext.language}${projectContext.framework ? ` (${projectContext.framework})` : ""}\n**Type**: ${projectContext.projectType}\n**Tech Stack**: ${projectContext.techStack.languages.join(", ")}${projectContext.techStack.frameworks.length > 0 ? `, ${projectContext.techStack.frameworks.join(", ")}` : ""}`,
    scenarios,
    business: businessPlane,
    data: dataPlane,
    control: controlPlane,
    foundation: foundationPlane,
    observation: observationPlane,
    security: securityPlane,
    evolution: evolutionPlane,
    crossPlaneDependencies: [
      "- Business Plane → needs → Data Plane",
      "- Data Plane → feeds → Observation Plane",
      "- Control Plane → manages → Business Plane",
      "- Foundation Plane → supports → All Planes",
      "- Security Plane → protects → All Planes",
    ],
    keyDecisions: generateKeyDecisions(projectContext, request, requestType),
    openQuestions: [
      `- Validate assumption: existing patterns are ${projectContext.patterns.length > 0 ? "appropriate" : "need to be defined"}`,
      "- Review with QiaoChui for technical feasibility",
      "- Validate assumptions with stakeholders",
    ],
    notes: "- Ready for QiaoChui review",
  });
}

interface RequestType {
  category: "refactor" | "feature" | "api" | "test" | "security" | "performance" | "general";
  description: string;
  focusPlanes: string[];
}

/**
 * Analyze the type of request to customize content
 */
function analyzeRequestType(request: string): RequestType {
  if (request.includes("refactor") || request.includes("reorganize") || request.includes("restructure")) {
    return {
      category: "refactor",
      description: `Refactoring request: ${request}`,
      focusPlanes: ["Data", "Control", "Foundation"],
    };
  }
  
  if (request.includes("api") || request.includes("endpoint") || request.includes("rest")) {
    return {
      category: "api",
      description: `API Design: ${request}`,
      focusPlanes: ["Foundation", "Data", "Security"],
    };
  }
  
  if (request.includes("test") || request.includes("tdd") || request.includes("coverage")) {
    return {
      category: "test",
      description: `Test Implementation: ${request}`,
      focusPlanes: ["Observation", "Data", "Control"],
    };
  }
  
  if (request.includes("security") || request.includes("vulnerability") || request.includes("auth")) {
    return {
      category: "security",
      description: `Security Enhancement: ${request}`,
      focusPlanes: ["Security", "Control", "Foundation"],
    };
  }
  
  if (request.includes("performance") || request.includes("optimize") || request.includes("speed")) {
    return {
      category: "performance",
      description: `Performance Optimization: ${request}`,
      focusPlanes: ["Control", "Observation", "Data"],
    };
  }
  
  if (request.includes("add") || request.includes("new") || request.includes("create") || request.includes("implement")) {
    return {
      category: "feature",
      description: `New Feature: ${request}`,
      focusPlanes: ["Business", "Foundation", "Data"],
    };
  }
  
  return {
    category: "general",
    description: `Feature Request: ${request}`,
    focusPlanes: ["Business", "Data", "Control", "Foundation"],
  };
}

/**
 * Generate Business Plane content from project context
 */
function generateBusinessPlane(ctx: ProjectContext, request: string, reqType: RequestType): { process: string[]; rules: string[] } {
  const { language, framework, projectType, patterns } = ctx;
  
  const process: string[] = [
    "- User interaction flow",
    `- Feature: ${request}`,
  ];
  
  const rules: string[] = [
    "- Business constraints",
    "- Policy requirements",
  ];

  // Add language/framework specific rules
  if (language === "typescript") {
    process.push("- TypeScript type checking at compile time");
    rules.push("- Strict null checking enabled");
    rules.push("- ES2022+ target for modern features");
  }
  
  if (framework === "react") {
    process.push("- React component lifecycle management");
    rules.push("- Hooks-first pattern (useState, useEffect, useCallback)");
    rules.push("- Functional component only (no class components)");
  }
  
  if (framework === "express" || framework === "fastify") {
    process.push("- RESTful endpoint routing");
    process.push("- Middleware chain for request processing");
    rules.push("- JSON request/response format");
    rules.push("- Standard HTTP status codes");
  }
  
  if (framework === "gin" || framework === "fiber") {
    process.push("- Go HTTP routing");
    process.push("- Middleware for logging, auth, recovery");
    rules.push("- Context-based request handling");
    rules.push("- Error wrapping with stack traces");
  }

  // Request type specific
  if (reqType.category === "feature") {
    process.push("- Feature flag for gradual rollout");
    rules.push("- Backward compatibility with existing APIs");
  }
  
  if (reqType.category === "refactor") {
    process.push("- Incremental refactoring approach");
    process.push("- Parallel implementation and testing");
    rules.push("- Preserve public API contracts");
    rules.push("- No breaking changes");
  }

  return { process, rules };
}

/**
 * Generate Data Plane content from project context
 */
function generateDataPlane(ctx: ProjectContext, request: string, reqType: RequestType): { logic: string[]; state: string[] } {
  const { language, existingComponents } = ctx;
  
  const logic: string[] = [
    "- Core business logic",
    "- Data transformations",
  ];
  
  const state: string[] = [
    "- Entity state management",
    "- Persistent state",
  ];

  // Language specific patterns
  if (language === "typescript") {
    logic.push("- TypeScript strict mode for type safety");
    logic.push("- Zod/TypeBox for runtime validation");
    logic.push("- Immutable data patterns (const assertions, Readonly)");
    
    // Check for existing patterns
    if (ctx.patterns.includes("Union Types")) {
      logic.push("- Discriminated unions for type-safe state");
    }
    if (ctx.patterns.includes("Async/Await")) {
      logic.push("- Promise-based async operations");
    }
  }
  
  if (language === "go") {
    logic.push("- Go idiomatic error handling (return errors)");
    logic.push("- Structured logging with context");
    logic.push("- Value receivers for simple types, pointer receivers for structs");
    
    if (ctx.patterns.includes("Interface Types")) {
      logic.push("- Program to interfaces, not implementations");
      logic.push("- Define interfaces where needed, not in advance");
    }
    if (ctx.patterns.includes("Concurrency (Goroutines)")) {
      logic.push("- Concurrent operations with goroutines and channels");
      logic.push("- Use sync.WaitGroup or context for synchronization");
    }
  }

  // Component specific
  if (existingComponents.length > 0) {
    const uniqueComponents = [...new Set(existingComponents)];
    logic.push(`- Existing components: ${uniqueComponents.join(", ")}`);
  }

  // Request type specific
  if (reqType.category === "api") {
    logic.push("- Request/Response DTOs");
    logic.push("- Data validation in handler layer");
    logic.push("- Business logic separated from HTTP concerns");
  }
  
  if (reqType.category === "test") {
    logic.push("- Test fixtures and mock data");
    logic.push("- Assertion helpers for common patterns");
    state.push("- Mock state for deterministic tests");
  }

  return { logic, state };
}

/**
 * Generate Control Plane content from project context
 */
function generateControlPlane(ctx: ProjectContext, request: string, reqType: RequestType): { strategy: string[]; distribution: string[] } {
  const { framework, language } = ctx;
  
  const strategy: string[] = [
    "- Decision points",
    "- Error handling strategy",
  ];
  
  const distribution: string[] = [
    "- Component communication",
    "- Event flow",
  ];

  // Framework specific control flow
  if (framework === "react") {
    strategy.push("- Unidirectional data flow (parent → child)");
    strategy.push("- State lifting for shared state");
    strategy.push("- Composition over inheritance");
    distribution.push("- Props drilling or Context for cross-component data");
  }
  
  if (framework === "express" || framework === "fastify") {
    strategy.push("- Middleware pattern for cross-cutting concerns");
    strategy.push("- Next() pattern for request flow control");
    distribution.push("- Route handlers as middleware chain");
  }
  
  if (framework === "gin" || framework === "fiber") {
    strategy.push("- Group-based routing for related endpoints");
    strategy.push("- Panic recovery middleware");
    distribution.push("- Handler functions with context");
  }

  // Language specific
  if (language === "typescript") {
    strategy.push("- Conditional rendering based on state");
    strategy.push("- Early returns for error cases");
  }
  
  if (language === "go") {
    strategy.push("- Explicit error checking (no try/catch)");
    strategy.push("- Deferred cleanup for resources");
    strategy.push("- Context for cancellation and timeouts");
    distribution.push("- Channel-based communication");
    distribution.push("- Select statement for multi-way control");
  }

  // Request type specific
  if (reqType.category === "performance") {
    strategy.push("- Memoization for expensive computations");
    strategy.push("- Debouncing for frequent events");
    strategy.push("- Lazy loading for optional features");
  }
  
  if (reqType.category === "general" && request.includes("error")) {
    strategy.push("- Centralized error handler");
    strategy.push("- Typed error classes");
    strategy.push("- User-friendly error messages");
  }

  return { strategy, distribution };
}

/**
 * Generate Foundation Plane content from project context
 */
function generateFoundationPlane(ctx: ProjectContext, request: string, reqType: RequestType): { resource: string[]; abstraction: string[] } {
  const { language, framework, structure, keyFiles } = ctx;
  
  const resource: string[] = [
    "- Infrastructure needed",
    "- External dependencies",
  ];
  
  const abstraction: string[] = [
    "- Public interfaces",
    "- API contracts",
  ];

  // Language specific resources
  if (language === "typescript") {
    resource.push("- Node.js runtime environment");
    resource.push("- TypeScript compiler (tsc)");
    
    if (ctx.techStack.buildTools.includes("vite")) {
      resource.push("- Vite for fast HMR and builds");
    } else if (ctx.techStack.buildTools.includes("webpack")) {
      resource.push("- Webpack for bundling");
    }
    
    abstraction.push("- Module exports (named and default)");
    abstraction.push("- TypeScript interfaces and types");
  }
  
  if (language === "go") {
    resource.push("- Go toolchain (1.21+)");
    resource.push("- Go modules for dependency management");
    
    abstraction.push("- Package-level exports");
    abstraction.push("- Go interfaces (implicit implementation)");
    abstraction.push("- Error interface");
  }

  // Framework specific abstractions
  if (framework === "react") {
    abstraction.push("- React.Component interface");
    abstraction.push("- React.FC for functional components");
    abstraction.push("- HTML element types");
  }
  
  if (framework === "express" || framework === "gin") {
    abstraction.push("- Router interface");
    abstraction.push("- Handler function signature");
    abstraction.push("- Middleware function signature");
  }

  // Structure specific
  if (structure.srcDir) {
    resource.push(`- Source directory: ${structure.srcDir}`);
  }
  if (structure.mainFile) {
    resource.push(`- Entry point: ${structure.mainFile}`);
  }

  // Key files
  const configFiles = keyFiles.filter(f => f.purpose.includes("config") || f.purpose.includes("dependencies"));
  if (configFiles.length > 0) {
    resource.push(`- Config files: ${configFiles.map(f => basename(f.path)).join(", ")}`);
  }

  // Request type specific
  if (reqType.category === "api") {
    abstraction.push("- REST API endpoints");
    abstraction.push("- Request/Response types");
    abstraction.push("- Error response format");
    resource.push("- HTTP client or REST library");
  }
  
  if (reqType.category === "feature") {
    resource.push("- Feature flag system (if needed)");
    resource.push("- Configuration management");
  }

  return { resource, abstraction };
}

/**
 * Generate Observation Plane content from project context
 */
function generateObservationPlane(ctx: ProjectContext, request: string, reqType: RequestType): { data: string[]; analysis: string[] } {
  const { techStack, patterns } = ctx;
  
  const data: string[] = [
    "- Key metrics",
    "- Events to track",
  ];
  
  const analysis: string[] = [
    "- Monitoring strategy",
    "- Alerting rules",
  ];

  // Testing framework specific
  if (techStack.testing.includes("jest")) {
    data.push("- Jest test results");
    data.push("- Code coverage percentage");
    data.push("- Test execution time");
    analysis.push("- Coverage threshold alerts");
  } else if (techStack.testing.includes("vitest")) {
    data.push("- Vitest test results");
    data.push("- V8 coverage reports");
  } else if (techStack.testing.includes("pytest")) {
    data.push("- Pytest results and coverage");
    data.push("- Test discovery patterns");
  }

  // Logging patterns
  if (patterns.includes("Debug Logging")) {
    data.push("- Application logs");
    data.push("- Error stack traces");
    analysis.push("- Log aggregation (if using centralized logging)");
  }

  // Request type specific
  if (reqType.category === "performance") {
    data.push("- Response time histograms");
    data.push("- Memory usage metrics");
    data.push("- CPU utilization");
    analysis.push("- Performance regression alerts");
  }
  
  if (reqType.category === "test") {
    data.push("- Test pass/fail rate");
    data.push("- Flaky test detection");
    data.push("- Coverage trends over time");
    analysis.push("- Test execution time trends");
  }

  return { data, analysis };
}

/**
 * Generate Security Plane content from project context
 */
function generateSecurityPlane(ctx: ProjectContext, request: string, reqType: RequestType): { identity: string[]; permissions: string[] } {
  const { framework, language } = ctx;
  
  const identity: string[] = [
    "- User identification",
    "- Authentication mechanism",
  ];
  
  const permissions: string[] = [
    "- Access control model",
    "- Permission structure",
  ];

  // Framework specific security
  if (framework === "express" || framework === "fastify") {
    identity.push("- JWT token authentication");
    identity.push("- Session-based auth (if needed)");
    permissions.push("- Route-level authorization middleware");
    permissions.push("- RBAC (Role-Based Access Control)");
  }
  
  if (framework === "gin" || framework === "fiber") {
    identity.push("- JWT middleware for auth");
    identity.push("- Session management");
    permissions.push("- Middleware-based authorization");
    permissions.push("- Context-based permission checks");
  }

  // Language specific
  if (language === "typescript") {
    identity.push("- Input sanitization");
    identity.push("- XSS prevention in rendering");
    permissions.push("- Environment variable access control");
  }
  
  if (language === "go") {
    identity.push("- Environment-based secrets");
    identity.push("- Structured logging (no sensitive data in logs)");
    permissions.push("- File system permission checks");
  }

  // Request type specific
  if (reqType.category === "security") {
    identity.push("- Enhanced input validation");
    identity.push("- Rate limiting per user");
    permissions.push("- Audit logging for sensitive operations");
    permissions.push("- Secure password hashing (bcrypt/argon2)");
  }
  
  if (reqType.category === "api") {
    identity.push("- API key authentication");
    identity.push("- OAuth 2.0 client credentials (if applicable)");
    permissions.push("- Scope-based API access control");
    permissions.push("- CORS configuration");
  }

  return { identity, permissions };
}

/**
 * Generate Evolution Plane content from project context
 */
function generateEvolutionPlane(ctx: ProjectContext, request: string, reqType: RequestType): { time: string[]; change: string[] } {
  const { language, framework } = ctx;
  
  const time: string[] = [
    "- Feature timeline",
    "- Milestone schedule",
  ];
  
  const change: string[] = [
    "- Versioning strategy",
    "- Migration approach",
  ];

  // Package manager specific versioning
  if (ctx.structure.hasPackageJson) {
    time.push("- npm/semver versioning");
    change.push("- Changelog maintained with conventional commits");
  }
  
  if (ctx.structure.hasGoMod) {
    time.push("- Go module versioning (v0, v1, v2...)");
    change.push("- Go proxy for reproducible builds");
  }

  // Framework specific evolution
  if (framework === "next" || framework === "nuxt") {
    time.push("- Incremental static regeneration");
    time.push("- Gradual deployment with feature flags");
  }
  
  if (framework === "react") {
    change.push("- React version upgrade path");
    change.push("- StrictMode for deprecation warnings");
  }

  // Request type specific
  if (reqType.category === "refactor") {
    time.push("- Phased refactoring with stable releases");
    time.push("- Parallel branch for breaking changes");
    change.push("- Migration scripts for data if needed");
    change.push("- Deprecation warnings in old code");
  }
  
  if (reqType.category === "feature") {
    time.push("- MVP first, then iterate");
    time.push("- Feature flags for controlled rollout");
    change.push("- Backward-compatible additions");
  }

  return { time, change };
}

/**
 * Generate starter Given/When/Then scenarios from request + project context.
 * These map 1:1 to TDD Red phases in LuBan. The agent/user refines them.
 *
 * Default coverage: 1 normal path + 1 error/validation path + 1 edge case.
 * Overridden by user-provided scenarios if any are passed via config.
 */
function generateScenarios(
  ctx: ProjectContext,
  request: string,
  reqType: RequestType,
): Scenario[] {
  const projectLabel = ctx.projectName || "the system";
  const featureHint = request.length > 80 ? `${request.slice(0, 77)}...` : request;

  // Starter set: normal + error + edge. Each is concrete and verifiable.
  const starters: Record<RequestType["category"], Scenario[]> = {
    feature: [
      {
        name: "happy path",
        given: `user invokes the new ${featureHint}`,
        when: "all preconditions are met",
        then: `${projectLabel} returns the expected successful result`,
      },
      {
        name: "invalid input",
        given: "user provides malformed or missing required input",
        when: "the action is triggered",
        then: `${projectLabel} returns a clear validation error and does not perform the action`,
      },
      {
        name: "boundary",
        given: "input is at the smallest or largest acceptable value",
        when: "the action is triggered",
        then: `${projectLabel} handles the boundary correctly (accepts the limit, rejects one past it)`,
      },
    ],
    refactor: [
      {
        name: "behavior preserved",
        given: "an existing caller uses the public API of the module being refactored",
        when: "the refactored implementation runs the same call",
        then: "the observable output is identical to the pre-refactor behavior",
      },
      {
        name: "internal API unchanged",
        given: "consumers depend on internal types or contracts",
        when: "the refactor is applied",
        then: "no breaking changes are introduced; tests still pass without modification",
      },
      {
        name: "performance delta",
        given: "the previous baseline metric is recorded",
        when: "the refactored code runs the same workload",
        then: `performance is within acceptable bounds (no regression > X%)`,
      },
    ],
    api: [
      {
        name: "valid request",
        given: "client sends a well-formed request with valid auth",
        when: "the endpoint is called",
        then: "the API returns 2xx with the expected response body",
      },
      {
        name: "invalid request",
        given: "client sends a malformed or unauthorized request",
        when: "the endpoint is called",
        then: "the API returns 4xx with a structured error message",
      },
      {
        name: "rate limit / degradation",
        given: "the service is under load or a downstream is unavailable",
        when: "the endpoint is called",
        then: "the API returns 5xx or a degraded response per the fallback strategy",
      },
    ],
    test: [
      {
        name: "test passes for valid input",
        given: "the system is in a known-good state",
        when: "the new test case is executed",
        then: "the assertion succeeds",
      },
      {
        name: "test fails for invalid input",
        given: "the system is in a known-bad state",
        when: "a regression test is executed",
        then: "the assertion fails with a clear message",
      },
      {
        name: "coverage target met",
        given: "the full test suite is run with coverage",
        when: "the new code paths are exercised",
        then: "coverage meets the agreed threshold (e.g., ≥80%)",
      },
    ],
    security: [
      {
        name: "authenticated access allowed",
        given: "a properly authenticated user with the required role",
        when: "the protected resource is accessed",
        then: "access is granted and the action is logged",
      },
      {
        name: "unauthenticated access denied",
        given: "an unauthenticated or unauthorized request",
        when: "the protected resource is accessed",
        then: "access is denied with a 401/403 and no sensitive data is leaked",
      },
      {
        name: "injection attempt blocked",
        given: "an attacker sends a crafted payload (SQLi/XSS/command injection)",
        when: "the input reaches the trust boundary",
        then: "the payload is rejected or sanitized; no execution occurs",
      },
    ],
    performance: [
      {
        name: "target metric met",
        given: "the system is under expected production load",
        when: "the optimized code path is exercised",
        then: `the target metric (latency/throughput/memory) meets the agreed SLO`,
      },
      {
        name: "no regression on cold path",
        given: "a previously slow path is still in use",
        when: "the optimization is deployed",
        then: "the cold path is not slower than before",
      },
      {
        name: "resource bounds respected",
        given: "sustained high load",
        when: "the system runs for an extended period",
        then: "memory and CPU stay within bounds (no leaks or runaway growth)",
      },
    ],
    general: [
      {
        name: "happy path",
        given: "the system is in a normal state",
        when: "the requested change is exercised",
        then: `${projectLabel} behaves as intended`,
      },
      {
        name: "error path",
        given: "an error condition occurs (bad input, missing dependency, etc.)",
        when: "the requested change is exercised",
        then: `${projectLabel} reports a clear error and does not corrupt state`,
      },
      {
        name: "edge case",
        given: "an unusual but legal condition (empty, max size, concurrent, etc.)",
        when: "the requested change is exercised",
        then: `${projectLabel} handles it gracefully`,
      },
    ],
  };

  return starters[reqType.category] || starters.general;
}

/**
 * Generate starter KeyDecisions from request + project context.
 * Each decision has placeholders the agent/user must fill in (alternatives, rationale).
 * The structure forces considering trade-offs before committing.
 */
function generateKeyDecisions(
  ctx: ProjectContext,
  request: string,
  reqType: RequestType,
): KeyDecision[] {
  const language = ctx.language || "unknown";
  const framework = ctx.framework || "no framework";

  return [
    {
      id: "KD-1",
      decision: `Use ${language}${framework !== "no framework" ? ` with ${framework}` : ""}`,
      context: `Request asks for ${reqType.category} work in a ${ctx.projectType || "unknown"} project`,
      alternatives: [
        { option: language, pros: "matches existing codebase", cons: "may not be ideal for this task" },
        { option: "switch language/framework", pros: "may be a better fit", cons: "high migration cost" },
      ],
      rationale: `_FILL IN: why this language/framework is appropriate for the request_`,
      enforcedBy: "typecheck + code review",
    },
    {
      id: "KD-2",
      decision: `Follow existing project patterns: ${ctx.patterns.slice(0, 3).join(", ") || "TBD"}`,
      context: `Existing patterns detected: ${ctx.patterns.join(", ") || "none"}. Project has components: ${ctx.existingComponents.join(", ") || "none"}.`,
      alternatives: [
        { option: "follow existing patterns", pros: "consistency, lower friction", cons: "may inherit existing limitations" },
        { option: "introduce new pattern", pros: "may be cleaner", cons: "cognitive overhead, inconsistency" },
      ],
      rationale: `_FILL IN: why existing patterns are appropriate OR why a new pattern is needed_`,
      enforcedBy: "code review",
    },
    {
      id: "KD-3",
      decision: `_FILL IN: the most important design choice for this ${reqType.category} request_`,
      context: `_FILL IN: what constraint or goal forces this decision_`,
      alternatives: [
        { option: "option A", pros: "_FILL IN_", cons: "_FILL IN_" },
        { option: "option B", pros: "_FILL IN_", cons: "_FILL IN_" },
      ],
      rationale: `_FILL IN: why the chosen option wins_`,
      enforcedBy: "_FILL IN: code review | lint | test | type check_",
    },
  ];
}

/**
 * Minimal draft generation (for backward compatibility)
 */
export function generateMinimalDraft(name: string, request: string): string {
  const analysis = analyzeRequest(request);

  return generateDraft({
    name,
    request,
    intent: analysis.intent,
    business: {
      process: analysis.businessProcess,
      rules: analysis.businessRules,
    },
    data: {
      logic: analysis.dataLogic,
      state: analysis.dataState,
    },
    control: {
      strategy: analysis.controlStrategy,
      distribution: analysis.controlDistribution,
    },
    foundation: {
      resource: analysis.foundationResource,
      abstraction: analysis.foundationAbstraction,
    },
    observation: {
      data: analysis.observationData,
      analysis: analysis.observationAnalysis,
    },
    security: {
      identity: analysis.securityIdentity,
      permissions: analysis.securityPermissions,
    },
    evolution: {
      time: analysis.evolutionTime,
      change: analysis.evolutionChange,
    },
    crossPlaneDependencies: [
      "- Business Plane → needs → Data Plane",
      "- Data Plane → feeds → Observation Plane",
      "- Control Plane → manages → Business Plane",
      "- Foundation Plane → supports → All Planes",
    ],
    keyDecisions: [
      {
        id: "KD-1",
        decision: "Focus on high-impact planes first",
        context: "MDD has 7 planes; not all apply to every request",
        alternatives: [
          { option: "all 7 planes", pros: "comprehensive", cons: "overkill for simple tasks" },
          { option: "focused subset", pros: "faster, more relevant", cons: "may miss cross-plane concerns" },
        ],
        rationale: "_FILL IN: which planes are most relevant and why_",
        enforcedBy: "code review",
      },
    ],
    openQuestions: [
      "- Review with QiaoChui for technical feasibility",
      "- Validate assumptions with stakeholders",
    ],
    notes: "- Ready for QiaoChui review",
  });
}

/**
 * Analyze request to generate relevant MDD plane content (legacy)
 */
function analyzeRequest(request: string): {
  intent: string;
  businessProcess: string[];
  businessRules: string[];
  dataLogic: string[];
  dataState: string[];
  controlStrategy: string[];
  controlDistribution: string[];
  foundationResource: string[];
  foundationAbstraction: string[];
  observationData: string[];
  observationAnalysis: string[];
  securityIdentity: string[];
  securityPermissions: string[];
  evolutionTime: string[];
  evolutionChange: string[];
} {
  const lowerRequest = request.toLowerCase();

  // Refactor request
  if (lowerRequest.includes("refactor")) {
    return {
      intent: `Refactor: ${request}`,
      businessProcess: [
        "- Analyze current code structure",
        "- Identify refactoring targets",
        "- Execute refactoring in stages",
        "- Validate with tests",
      ],
      businessRules: [
        "- Preserve public API contracts",
        "- No breaking changes to existing interfaces",
        "- Maintain backward compatibility",
      ],
      dataLogic: [
        "- Code structure analysis",
        "- Dependency mapping",
        "- Pattern detection",
      ],
      dataState: [
        "- Module state preservation",
        "- Dependency graph state",
      ],
      controlStrategy: [
        "- Incremental refactoring approach",
        "- Feature flag for risky changes",
      ],
      controlDistribution: [
        "- File-level refactoring tasks",
        "- Module-level dependencies",
      ],
      foundationResource: [
        "- Development environment",
        "- Test infrastructure",
      ],
      foundationAbstraction: [
        "- Public API boundaries",
        "- Internal module interfaces",
      ],
      observationData: [
        "- Test pass/fail metrics",
        "- Code coverage",
        "- Build times",
      ],
      observationAnalysis: [
        "- Regression detection",
        "- Performance impact analysis",
      ],
      securityIdentity: [
        "- Developer authentication (git)",
      ],
      securityPermissions: [
        "- Code review requirements",
        "- Merge approval rules",
      ],
      evolutionTime: [
        "- Phased rollout timeline",
        "- Deprecation schedules",
      ],
      evolutionChange: [
        "- Version bump strategy",
        "- Changelog updates",
        "- Migration guides",
      ],
    };
  }

  // API/Endpoint request
  if (lowerRequest.includes("api") || lowerRequest.includes("endpoint") || lowerRequest.includes("rest")) {
    return {
      intent: `API Design: ${request}`,
      businessProcess: [
        "- Client request handling",
        "- Business logic execution",
        "- Response generation",
      ],
      businessRules: [
        "- Input validation rules",
        "- Authorization policies",
        "- Rate limiting policies",
      ],
      dataLogic: [
        "- Request routing",
        "- Data transformation",
        "- Business rule execution",
      ],
      dataState: [
        "- Request/Response state",
        "- Session state",
        "- Cached data",
      ],
      controlStrategy: [
        "- Authentication strategy",
        "- Authorization strategy",
        "- Error handling strategy",
      ],
      controlDistribution: [
        "- Request routing",
        "- Load balancing",
        "- Service discovery",
      ],
      foundationResource: [
        "- HTTP server",
        "- Database connections",
        "- External service clients",
      ],
      foundationAbstraction: [
        "- REST API contract",
        "- OpenAPI/Swagger spec",
        "- SDK interfaces",
      ],
      observationData: [
        "- Request/Response logs",
        "- Latency metrics",
        "- Error rates",
      ],
      observationAnalysis: [
        "- Performance dashboards",
        "- Error tracking",
        "- Usage analytics",
      ],
      securityIdentity: [
        "- API key authentication",
        "- OAuth2/JWT tokens",
        "- Session management",
      ],
      securityPermissions: [
        "- Role-based access control",
        "- Resource-level permissions",
      ],
      evolutionTime: [
        "- API versioning strategy",
        "- Deprecation timelines",
      ],
      evolutionChange: [
        "- Breaking vs non-breaking changes",
        "- Migration path documentation",
      ],
    };
  }

  // Testing request
  if (lowerRequest.includes("test") || lowerRequest.includes("tdd")) {
    return {
      intent: `Test Implementation: ${request}`,
      businessProcess: [
        "- Test planning",
        "- Test case design",
        "- Test execution",
        "- Results validation",
      ],
      businessRules: [
        "- Test coverage requirements",
        "- Pass/fail criteria",
        "- Regression thresholds",
      ],
      dataLogic: [
        "- Test assertion logic",
        "- Mock/stub setup",
        "- Fixture management",
      ],
      dataState: [
        "- Test fixture state",
        "- Mock object state",
        "- Cleanup handling",
      ],
      controlStrategy: [
        "- Test selection strategy",
        "- Parallel execution strategy",
        "- Retry strategy for flaky tests",
      ],
      controlDistribution: [
        "- Test distribution across workers",
        "- CI/CD pipeline integration",
      ],
      foundationResource: [
        "- Test framework",
        "- Mock library",
        "- CI/CD infrastructure",
      ],
      foundationAbstraction: [
        "- Test interface contracts",
        "- Assertion libraries",
      ],
      observationData: [
        "- Test results",
        "- Coverage reports",
        "- Execution times",
      ],
      observationAnalysis: [
        "- Flaky test detection",
        "- Coverage analysis",
        "- Trend analysis",
      ],
      securityIdentity: [
        "- CI/CD authentication",
      ],
      securityPermissions: [
        "- Repository access for test results",
      ],
      evolutionTime: [
        "- Test maintenance schedule",
        "- Legacy test migration",
      ],
      evolutionChange: [
        "- Test refactoring strategy",
        "- Framework upgrade path",
      ],
    };
  }

  // Default generic request
  return {
    intent: request,
    businessProcess: [
      "- User interaction flow",
      "- Core workflow steps",
    ],
    businessRules: [
      "- Business constraints",
      "- Policy requirements",
    ],
    dataLogic: [
      "- Core business logic",
      "- Data transformations",
    ],
    dataState: [
      "- Entity state management",
      "- Persistent state",
    ],
    controlStrategy: [
      "- Decision points",
      "- Error handling strategy",
    ],
    controlDistribution: [
      "- Component communication",
      "- Event flow",
    ],
    foundationResource: [
      "- Infrastructure needed",
      "- External dependencies",
    ],
    foundationAbstraction: [
      "- Public interfaces",
      "- API contracts",
    ],
    observationData: [
      "- Key metrics",
      "- Events to track",
    ],
    observationAnalysis: [
      "- Monitoring strategy",
      "- Alerting rules",
    ],
    securityIdentity: [
      "- User identification",
      "- Authentication mechanism",
    ],
    securityPermissions: [
      "- Access control model",
      "- Permission structure",
    ],
    evolutionTime: [
      "- Feature timeline",
      "- Milestone schedule",
    ],
    evolutionChange: [
      "- Versioning strategy",
      "- Migration approach",
    ],
  };
}

// Helper to get basename
function basename(path: string): string {
  return path.split("/").pop() || path;
}