/**
 * Draft Generator - Creates MDD (Multi-Dimensional Design) drafts
 * Based on Fuxi's Seven Planes methodology
 */

export interface DraftConfig {
  name: string;
  request: string;
  intent?: string;
  // MDD Planes
  business?: {
    process?: string[];
    rules?: string[];
  };
  data?: {
    logic?: string[];
    state?: string[];
  };
  control?: {
    strategy?: string[];
    distribution?: string[];
  };
  foundation?: {
    resource?: string[];
    abstraction?: string[];
  };
  observation?: {
    data?: string[];
    analysis?: string[];
  };
  security?: {
    identity?: string[];
    permissions?: string[];
  };
  evolution?: {
    time?: string[];
    change?: string[];
  };
  crossPlaneDependencies?: string[];
  keyDecisions?: string[];
  openQuestions?: string[];
  notes?: string;
}

const DRAFT_TEMPLATE = `# System Design: {name}

## Overview
{intelligence}

---

## MDD Plane Analysis

### 1. Business Plane: Process × Rules
**Focus**: Business value delivery

**Process**
{process}

**Rules**
{rules}

---

### 2. Data Plane: Logic × State
**Focus**: Data processing and state management

**Logic**
{logic}

**State**
{state}

---

### 3. Control Plane: Strategy × Distribution
**Focus**: Decision making and execution

**Strategy**
{strategy}

**Distribution**
{distribution}

---

### 4. Foundation Plane: Resource × Abstraction
**Focus**: Infrastructure and encapsulation

**Resource**
{resource}

**Abstraction**
{abstraction}

---

### 5. Observation Plane: Data × Analysis
**Focus**: Monitoring and insights

**Data**
{obsData}

**Analysis**
{analysis}

---

### 6. Security Plane: Identity × Permissions
**Focus**: Authentication and authorization

**Identity**
{identity}

**Permissions**
{permissions}

---

### 7. Evolution Plane: Time × Change
**Focus**: System evolution and versioning

**Time**
{time}

**Change**
{change}

---

## Cross-Plane Dependencies

{crossPlaneDeps}

---

## Key Design Decisions

{keyDecisions}

---

## Open Questions

{openQuestions}

---

## Notes

{notes}

---

*Generated by Fuxi (伏羲) - Multi-Dimensional Design*
*Timestamp: {timestamp}*
`;

export function generateDraft(config: DraftConfig): string {
  const timestamp = new Date().toISOString();

  const formatList = (items?: string[]) => {
    if (!items || items.length === 0) return "- None specified";
    return items.map(item => `- ${item}`).join("\n");
  };

  return DRAFT_TEMPLATE
    .replace("{name}", config.name)
    .replace("{timestamp}", timestamp)
    .replace("{intelligence}", config.intent || config.request)
    // Business Plane
    .replace("{process}", formatList(config.business?.process))
    .replace("{rules}", formatList(config.business?.rules))
    // Data Plane
    .replace("{logic}", formatList(config.data?.logic))
    .replace("{state}", formatList(config.data?.state))
    // Control Plane
    .replace("{strategy}", formatList(config.control?.strategy))
    .replace("{distribution}", formatList(config.control?.distribution))
    // Foundation Plane
    .replace("{resource}", formatList(config.foundation?.resource))
    .replace("{abstraction}", formatList(config.foundation?.abstraction))
    // Observation Plane
    .replace("{obsData}", formatList(config.observation?.data))
    .replace("{analysis}", formatList(config.observation?.analysis))
    // Security Plane
    .replace("{identity}", formatList(config.security?.identity))
    .replace("{permissions}", formatList(config.security?.permissions))
    // Evolution Plane
    .replace("{time}", formatList(config.evolution?.time))
    .replace("{change}", formatList(config.evolution?.change))
    // Cross-cutting
    .replace("{crossPlaneDeps}", formatList(config.crossPlaneDependencies))
    .replace("{keyDecisions}", formatList(config.keyDecisions))
    .replace("{openQuestions}", formatList(config.openQuestions))
    .replace("{notes}", config.notes || "- Add notes here");
}

export function generateMinimalDraft(name: string, request: string): string {
  const analysis = analyzeRequest(request);

  return generateDraft({
    name,
    request,
    intent: analysis.intent,
    business: {
      process: analysis.businessProcess,
      rules: analysis.businessRules,
    },
    data: {
      logic: analysis.dataLogic,
      state: analysis.dataState,
    },
    control: {
      strategy: analysis.controlStrategy,
      distribution: analysis.controlDistribution,
    },
    foundation: {
      resource: analysis.foundationResource,
      abstraction: analysis.foundationAbstraction,
    },
    observation: {
      data: analysis.observationData,
      analysis: analysis.observationAnalysis,
    },
    security: {
      identity: analysis.securityIdentity,
      permissions: analysis.securityPermissions,
    },
    evolution: {
      time: analysis.evolutionTime,
      change: analysis.evolutionChange,
    },
    crossPlaneDependencies: [
      "- Business Plane → needs → Data Plane",
      "- Data Plane → feeds → Observation Plane",
      "- Control Plane → manages → Business Plane",
      "- Foundation Plane → supports → All Planes",
    ],
    keyDecisions: [
      "- Focus on high-impact planes first",
      "- Apply relevant planes only (not all 7 may apply)",
    ],
    openQuestions: [
      "- Review with QiaoChui for technical feasibility",
      "- Validate assumptions with stakeholders",
    ],
    notes: "- Ready for QiaoChui review",
  });
}

/**
 * Analyze request to generate relevant MDD plane content
 */
function analyzeRequest(request: string): {
  intent: string;
  businessProcess: string[];
  businessRules: string[];
  dataLogic: string[];
  dataState: string[];
  controlStrategy: string[];
  controlDistribution: string[];
  foundationResource: string[];
  foundationAbstraction: string[];
  observationData: string[];
  observationAnalysis: string[];
  securityIdentity: string[];
  securityPermissions: string[];
  evolutionTime: string[];
  evolutionChange: string[];
} {
  const lowerRequest = request.toLowerCase();

  // Refactor request
  if (lowerRequest.includes("refactor")) {
    return {
      intent: `Refactor: ${request}`,
      businessProcess: [
        "- Analyze current code structure",
        "- Identify refactoring targets",
        "- Execute refactoring in stages",
        "- Validate with tests",
      ],
      businessRules: [
        "- Preserve public API contracts",
        "- No breaking changes to existing interfaces",
        "- Maintain backward compatibility",
      ],
      dataLogic: [
        "- Code structure analysis",
        "- Dependency mapping",
        "- Pattern detection",
      ],
      dataState: [
        "- Module state preservation",
        "- Dependency graph state",
      ],
      controlStrategy: [
        "- Incremental refactoring approach",
        "- Feature flag for risky changes",
      ],
      controlDistribution: [
        "- File-level refactoring tasks",
        "- Module-level dependencies",
      ],
      foundationResource: [
        "- Development environment",
        "- Test infrastructure",
      ],
      foundationAbstraction: [
        "- Public API boundaries",
        "- Internal module interfaces",
      ],
      observationData: [
        "- Test pass/fail metrics",
        "- Code coverage",
        "- Build times",
      ],
      observationAnalysis: [
        "- Regression detection",
        "- Performance impact analysis",
      ],
      securityIdentity: [
        "- Developer authentication (git)",
      ],
      securityPermissions: [
        "- Code review requirements",
        "- Merge approval rules",
      ],
      evolutionTime: [
        "- Phased rollout timeline",
        "- Deprecation schedules",
      ],
      evolutionChange: [
        "- Version bump strategy",
        "- Changelog updates",
        "- Migration guides",
      ],
    };
  }

  // API/Endpoint request
  if (lowerRequest.includes("api") || lowerRequest.includes("endpoint") || lowerRequest.includes("rest")) {
    return {
      intent: `API Design: ${request}`,
      businessProcess: [
        "- Client request handling",
        "- Business logic execution",
        "- Response generation",
      ],
      businessRules: [
        "- Input validation rules",
        "- Authorization policies",
        "- Rate limiting policies",
      ],
      dataLogic: [
        "- Request routing",
        "- Data transformation",
        "- Business rule execution",
      ],
      dataState: [
        "- Request/Response state",
        "- Session state",
        "- Cached data",
      ],
      controlStrategy: [
        "- Authentication strategy",
        "- Authorization strategy",
        "- Error handling strategy",
      ],
      controlDistribution: [
        "- Request routing",
        "- Load balancing",
        "- Service discovery",
      ],
      foundationResource: [
        "- HTTP server",
        "- Database connections",
        "- External service clients",
      ],
      foundationAbstraction: [
        "- REST API contract",
        "- OpenAPI/Swagger spec",
        "- SDK interfaces",
      ],
      observationData: [
        "- Request/Response logs",
        "- Latency metrics",
        "- Error rates",
      ],
      observationAnalysis: [
        "- Performance dashboards",
        "- Error tracking",
        "- Usage analytics",
      ],
      securityIdentity: [
        "- API key authentication",
        "- OAuth2/JWT tokens",
        "- Session management",
      ],
      securityPermissions: [
        "- Role-based access control",
        "- Resource-level permissions",
      ],
      evolutionTime: [
        "- API versioning strategy",
        "- Deprecation timelines",
      ],
      evolutionChange: [
        "- Breaking vs non-breaking changes",
        "- Migration path documentation",
      ],
    };
  }

  // Testing request
  if (lowerRequest.includes("test") || lowerRequest.includes("tdd")) {
    return {
      intent: `Test Implementation: ${request}`,
      businessProcess: [
        "- Test planning",
        "- Test case design",
        "- Test execution",
        "- Results validation",
      ],
      businessRules: [
        "- Test coverage requirements",
        "- Pass/fail criteria",
        "- Regression thresholds",
      ],
      dataLogic: [
        "- Test assertion logic",
        "- Mock/stub setup",
        "- Fixture management",
      ],
      dataState: [
        "- Test fixture state",
        "- Mock object state",
        "- Cleanup handling",
      ],
      controlStrategy: [
        "- Test selection strategy",
        "- Parallel execution strategy",
        "- Retry strategy for flaky tests",
      ],
      controlDistribution: [
        "- Test distribution across workers",
        "- CI/CD pipeline integration",
      ],
      foundationResource: [
        "- Test framework",
        "- Mock library",
        "- CI/CD infrastructure",
      ],
      foundationAbstraction: [
        "- Test interface contracts",
        "- Assertion libraries",
      ],
      observationData: [
        "- Test results",
        "- Coverage reports",
        "- Execution times",
      ],
      observationAnalysis: [
        "- Flaky test detection",
        "- Coverage analysis",
        "- Trend analysis",
      ],
      securityIdentity: [
        "- CI/CD authentication",
      ],
      securityPermissions: [
        "- Repository access for test results",
      ],
      evolutionTime: [
        "- Test maintenance schedule",
        "- Legacy test migration",
      ],
      evolutionChange: [
        "- Test refactoring strategy",
        "- Framework upgrade path",
      ],
    };
  }

  // Default generic request
  return {
    intent: request,
    businessProcess: [
      "- User interaction flow",
      "- Core workflow steps",
    ],
    businessRules: [
      "- Business constraints",
      "- Policy requirements",
    ],
    dataLogic: [
      "- Core business logic",
      "- Data transformations",
    ],
    dataState: [
      "- Entity state management",
      "- Persistent state",
    ],
    controlStrategy: [
      "- Decision points",
      "- Error handling strategy",
    ],
    controlDistribution: [
      "- Component communication",
      "- Event flow",
    ],
    foundationResource: [
      "- Infrastructure needed",
      "- External dependencies",
    ],
    foundationAbstraction: [
      "- Public interfaces",
      "- API contracts",
    ],
    observationData: [
      "- Key metrics",
      "- Events to track",
    ],
    observationAnalysis: [
      "- Monitoring strategy",
      "- Alerting rules",
    ],
    securityIdentity: [
      "- User identification",
      "- Authentication mechanism",
    ],
    securityPermissions: [
      "- Access control model",
      "- Permission structure",
    ],
    evolutionTime: [
      "- Feature timeline",
      "- Milestone schedule",
    ],
    evolutionChange: [
      "- Versioning strategy",
      "- Migration approach",
    ],
  };
}
