/**
 * QiaoChui Tools - Review and decomposition phase tools
 * Files are saved to .sages/workspace/
 */

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { Type } from "typebox";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { parseDraft, validateDraft, generateTasksFromDraft } from "../utils/draft-parser.js";

const WORKSPACE_DIR = ".sages/workspace";

export function registerQiaoChuiTools(pi: ExtensionAPI): void {
  pi.registerTool({
    name: "qiaochui_review",
    label: "Review Draft",
    description: "QiaoChui reviews Fuxi's design draft for feasibility",
    parameters: Type.Object({
      draft_path: Type.String({ description: "Path to the draft file (default: .sages/workspace/draft.md)" }),
    }),
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const cwd = ctx.cwd;
      const draft_path = params.draft_path || join(cwd, WORKSPACE_DIR, "draft.md");

      try {
        if (!existsSync(draft_path)) {
          return {
            content: [{ type: "text", text: JSON.stringify({ success: false, error: { message: `Draft not found: ${draft_path}` } }) }],
            isError: true,
            details: { draft_path },
          };
        }

        const content = readFileSync(draft_path, "utf-8");
        const validation = validateDraft(content);

        if (!validation.valid) {
          return {
            content: [{
              type: "text",
              text: JSON.stringify({
                success: true,
                verdict: "REVISE",
                issues: validation.issues,
                recommendations: ["Fill in missing sections", "Remove placeholders"],
              }),
            }],
            details: { draft_path, verdict: "REVISE", issues: validation.issues },
          };
        }

        const parsed = parseDraft(content, "workflow");
        const taskCount = parsed ? generateTasksFromDraft(parsed).length : 5;

        return {
          content: [{
            type: "text",
            text: JSON.stringify({
              success: true,
              verdict: "APPROVED",
              parsed: parsed !== null,
              taskCount,
              estimatedTime: parsed ? 30 : 45,
              recommendations: ["Design is well-structured", "Ready for task decomposition"],
            }),
          }],
          details: { draft_path, verdict: "APPROVED", parsed: parsed !== null, taskCount },
        };
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: JSON.stringify({ success: false, error: { message: msg } }) }],
          isError: true,
          details: { error: msg },
        };
      }
    },
  });

  pi.registerTool({
    name: "qiaochui_decompose",
    label: "Decompose",
    description: "QiaoChui decomposes the approved design into executable tasks (saves to .sages/workspace/)",
    parameters: Type.Object({
      draft_path: Type.Optional(Type.String({ description: "Draft path (default: .sages/workspace/draft.md)" })),
      max_tasks: Type.Optional(Type.Number({ description: "Max tasks to generate (default: 10)" })),
      use_subagent: Type.Optional(Type.Boolean({ description: "Use isolated subagent mode for parallel execution (default: true)" })),
      max_parallel: Type.Optional(Type.Number({ description: "Max parallel subagents (default: 3)" })),
    }),
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const cwd = ctx.cwd;
      const draft_path = params.draft_path || join(cwd, WORKSPACE_DIR, "draft.md");
      const max_tasks = params.max_tasks || 10;
      const use_subagent = params.use_subagent !== false; // Default: true
      const max_parallel = params.max_parallel || 3;

      try {
        if (!existsSync(draft_path)) {
          return {
            content: [{ type: "text", text: JSON.stringify({ success: false, error: { message: `Draft not found: ${draft_path}` } }) }],
            isError: true,
            details: { draft_path },
          };
        }

        const content = readFileSync(draft_path, "utf-8");
        const workspacePath = join(cwd, WORKSPACE_DIR);

        if (!existsSync(workspacePath)) {
          mkdirSync(workspacePath, { recursive: true });
        }

        const parsed = parseDraft(content, "workflow");
        let tasks = parsed 
          ? generateTasksFromDraft(parsed).slice(0, max_tasks)
          : generateDefaultTasks().slice(0, max_tasks);

        let planName = "workflow";
        
        let planMarkdown = `# Task Plan\n\nGenerated by: QiaoChui (巧倕)\nTimestamp: ${new Date().toISOString()}\n\n## Tasks\n\n`;
        for (const task of tasks) {
          planMarkdown += `### ${task.id}: ${task.description}\n`;
          planMarkdown += `- Priority: ${task.priority}\n`;
          if (task.dependsOn.length > 0) {
            planMarkdown += `- Depends on: ${task.dependsOn.join(", ")}\n`;
          }
          planMarkdown += "\n";
        }

        const totalTime = tasks.length * 10;
        planMarkdown += `## Total Estimated Time: ${totalTime} minutes\n`;

        const executionYaml = `# Execution Plan
# Generated by QiaoChui (巧倕) - Technical Expert
# Plan: ${planName}
# Created: ${new Date().toISOString()}

name: ${planName}

settings:
  maxParallel: ${max_parallel}
  useSubagent: ${use_subagent}
  maxRetry: 1
  subagentConfig:
    model: sonnet
    skills:
      - luban
    maxContext: 4000
    timeout: 300

tasks:
${tasks.map((t) => `  - id: ${t.id}
    description: "${t.description}"
    priority: ${t.priority === "high" ? 1 : t.priority === "medium" ? 2 : 3}
    dependsOn: [${t.dependsOn.map(d => `"${d}"`).join(", ")}]`).join("\n")}
`;

        const planPath = join(workspacePath, "plan.md");
        const executionPath = join(workspacePath, "execution.yaml");
        const tasksPath = join(workspacePath, "tasks.json");

        writeFileSync(planPath, planMarkdown);
        writeFileSync(executionPath, executionYaml);
        writeFileSync(tasksPath, JSON.stringify(tasks, null, 2));

        return {
          content: [{
            type: "text",
            text: JSON.stringify({
              success: true,
              plan_path: planPath,
              execution_path: executionPath,
              tasks_path: tasksPath,
              task_count: tasks.length,
              estimated_time: totalTime,
              execution_mode: {
                use_subagent: use_subagent,
                max_parallel: max_parallel,
                description: use_subagent
                  ? "Isolated subagent mode - each task runs in a separate pi process"
                  : "Shared context mode - all tasks share the same context",
              },
              workspace: workspacePath,
            }),
          }],
          details: { 
            planPath, 
            executionPath, 
            taskCount: tasks.length,
            useSubagent: use_subagent,
            maxParallel: max_parallel,
          },
        };
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: JSON.stringify({ success: false, error: { message: msg } }) }],
          isError: true,
          details: { error: msg },
        };
      }
    },
  });
}

function generateDefaultTasks() {
  return [
    { id: "T1", description: "Analyze requirements and understand the codebase", priority: "high" as const, dependsOn: [] },
    { id: "T2", description: "Design component structure", priority: "high" as const, dependsOn: ["T1"] },
    { id: "T3", description: "Implement core functionality", priority: "high" as const, dependsOn: ["T1", "T2"] },
    { id: "T4", description: "Add comprehensive tests", priority: "medium" as const, dependsOn: ["T3"] },
    { id: "T5", description: "Run final review", priority: "medium" as const, dependsOn: ["T4"] },
  ];
}
