/**
 * Integration Tests for Four Sages Agents Workflow Flow
 * 
 * Tests the complete workflow: Fuxi → QiaoChui → LuBan → GaoYao
 * This validates that each agent can properly pass data to the next.
 */

import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { existsSync, mkdirSync, rmSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { randomUUID } from "node:crypto";

// =============================================================================
// Test Fixtures
// =============================================================================

interface TestProject {
  path: string;
  name: string;
}

function createTestProject(): TestProject {
  const projectPath = join("/tmp", `sages-test-${randomUUID()}`);
  mkdirSync(projectPath, { recursive: true });
  mkdirSync(join(projectPath, ".sages", "plans"), { recursive: true });
  return { path: projectPath, name: "test-workflow" };
}

function cleanupTestProject(project: TestProject): void {
  try {
    rmSync(project.path, { recursive: true, force: true });
  } catch {
    // Ignore cleanup errors
  }
}

// =============================================================================
// Mock Context
// =============================================================================

interface MockContext {
  agent: string;
  sessionID: string;
  messageID: string;
}

function createMockContext(projectPath: string): MockContext {
  return {
    agent: projectPath,
    sessionID: `test-session-${randomUUID()}`,
    messageID: `test-msg-${randomUUID()}`,
  };
}

// =============================================================================
// Fuxi Flow Tests
// =============================================================================

describe("Fuxi - Design Draft Creation", () => {
  let project: TestProject;
  let ctx: MockContext;

  beforeEach(() => {
    project = createTestProject();
    ctx = createMockContext(project.path);
  });

  afterEach(() => {
    cleanupTestProject(project);
  });

  it("should create a design draft with Eight Trigrams structure", () => {
    const draftContent = `# Design Draft: ${project.name}

Generated by: Fuxi
Timestamp: ${new Date().toISOString()}
Status: draft

## ☰ Qian (Heaven) - Core Intent

Implement a user authentication system with JWT tokens.

## ☷ Kun (Earth) - Data Structures

- User { id, email, passwordHash, createdAt }
- Session { id, userId, token, expiresAt }

## ☳ Zhen (Thunder) - Trigger Mechanisms

- User login event
- Session expiry event
- Logout event

## ☴ Xun (Wind) - Data Flow

User → Login → Validate → JWT Issue → Session Store → Response

## ☵ Kan (Water) - Error Handling

- Invalid credentials → 401 response
- Expired token → Refresh token flow
- DB errors → 500 with retry

## ☲ Li (Fire) - Observability

- Login success/failure metrics
- Session creation rate
- Token refresh rate

## ☶ Gen (Mountain) - Boundaries

- No password recovery via email
- No third-party auth initially
- No social login

## ☱ Dui (Lake) - Success Path

User logs in → Receives JWT → Makes authenticated requests → Logs out

## Notes

MVP scope only.
`;

    const draftPath = join(project.path, ".sages", "plans", `${project.name}.draft.md`);
    writeFileSync(draftPath, draftContent);

    expect(existsSync(draftPath)).toBe(true);
    expect(draftContent).toContain("☰ Qian (Heaven) - Core Intent");
    expect(draftContent).toContain("☷ Kun (Earth) - Data Structures");
    expect(draftContent).toContain("☳ Zhen (Thunder) - Trigger Mechanisms");
  });

  it("should generate draft path correctly", () => {
    const draftPath = join(project.path, ".sages", "plans", `${project.name}.draft.md`);
    const expectedPattern = /\.sages\/plans\/test-workflow\.draft\.md$/;
    expect(draftPath).toMatch(expectedPattern);
  });
});

// =============================================================================
// QiaoChui Flow Tests
// =============================================================================

describe("QiaoChui - Design Review and Task Decomposition", () => {
  let project: TestProject;
  let ctx: MockContext;

  beforeEach(() => {
    project = createTestProject();
    ctx = createMockContext(project.path);
  });

  afterEach(() => {
    cleanupTestProject(project);
  });

  it("should review draft and return APPROVED verdict for complete drafts", () => {
    // Create a complete draft
    const draftContent = `# Design Draft: test

## ☰ Qian (Heaven) - Core Intent
Build auth system

## ☷ Kun (Earth) - Data Structures
User, Session entities

## ☳ Zhen (Thunder) - Triggers
Login, logout

## ☴ Xun (Wind) - Flow
User → Auth → JWT

## ☵ Kan (Water) - Error
Handle failures

## ☲ Li (Fire) - Observe
Log events

## ☶ Gen (Mountain) - Bounds
No third-party auth

## ☱ Dui (Lake) - Success
Successful login

## Notes
MVP only
`;
    const draftPath = join(project.path, ".sages", "plans", "test.draft.md");
    writeFileSync(draftPath, draftContent);

    // Verify draft exists and has all Eight Trigrams sections
    expect(existsSync(draftPath)).toBe(true);
    
    // Count sections
    const sections = [
      "☰ Qian", "☷ Kun", "☳ Zhen", "☴ Xun", 
      "☵ Kan", "☲ Li", "☶ Gen", "☱ Dui"
    ];
    let sectionCount = 0;
    for (const section of sections) {
      if (draftContent.includes(section)) sectionCount++;
    }
    expect(sectionCount).toBe(8);
  });

  it("should decompose draft into executable tasks", () => {
    const planContent = `# Task Plan: test

## Tasks

### T1: Analyze requirements and understand the codebase
- Priority: high
- Estimated time: 5 minutes
- Depends on: none

### T2: Design component structure
- Priority: high
- Estimated time: 10 minutes
- Depends on: T1

### T3: Implement core functionality
- Priority: high
- Estimated time: 15 minutes
- Depends on: T1, T2

### T4: Add comprehensive tests
- Priority: medium
- Estimated time: 10 minutes
- Depends on: T3

### T5: Run final review
- Priority: medium
- Estimated time: 5 minutes
- Depends on: T4

## Total Estimated Time: 45 minutes
`;

    const planPath = join(project.path, ".sages", "plans", "test.plan.md");
    writeFileSync(planPath, planContent);

    expect(existsSync(planPath)).toBe(true);
    
    // Verify task structure
    const taskMatches = planContent.match(/### T\d+:/g);
    expect(taskMatches).toHaveLength(5);
  });

  it("should generate execution YAML with phases", () => {
    const executionContent = `name: test

settings:
  maxParallel: 4
  maxFailure: 12
  retryAttempts: 3
  checkpointInterval: 300
  lockTimeout: 1800

phases:
  - name: Phase 1
    parallel: false
    maxParallel: 1
    tasks:
      - id: T1
        description: "Analyze requirements"
        agent: luban
        dependsOn: []
        priority: 1
        files: []
      - id: T2
        description: "Design structure"
        agent: luban
        dependsOn: ["T1"]
        priority: 1
        files: []
`;

    const executionPath = join(project.path, ".sages", "plans", "test.execution.yaml");
    writeFileSync(executionPath, executionContent);

    expect(existsSync(executionPath)).toBe(true);
    expect(executionContent).toContain("maxParallel: 4");
    expect(executionContent).toContain("T1");
    expect(executionContent).toContain("T2");
  });
});

// =============================================================================
// LuBan Flow Tests
// =============================================================================

describe("LuBan - Task Execution with TDD", () => {
  let project: TestProject;
  let ctx: MockContext;

  beforeEach(() => {
    project = createTestProject();
    ctx = createMockContext(project.path);
  });

  afterEach(() => {
    cleanupTestProject(project);
  });

  it("should acquire file locks before task execution", () => {
    const lockRegistry: Record<string, { taskId: string; lockedBy: string; lockedAt: string }> = {};
    
    function acquireLock(filePath: string, taskId: string): boolean {
      const key = `${taskId}:${filePath}`;
      if (lockRegistry[key]) return false;
      lockRegistry[key] = {
        taskId,
        lockedBy: taskId,
        lockedAt: new Date().toISOString()
      };
      return true;
    }

    // T1 acquires lock on src/index.ts
    expect(acquireLock("src/index.ts", "T1")).toBe(true);
    
    // T2 cannot acquire same file - same key "T2:src/index.ts" doesn't exist yet
    // But T1 already has "T1:src/index.ts" - different key
    // So we need to check differently - the actual lock should be checked by file path
    const locksByFile: Record<string, string> = {}; // filePath -> taskId
    
    function acquireLockWithConflictDetection(filePath: string, taskId: string): { success: boolean; conflict?: string } {
      if (locksByFile[filePath] && locksByFile[filePath] !== taskId) {
        return { success: false, conflict: locksByFile[filePath] };
      }
      locksByFile[filePath] = taskId;
      return { success: true };
    }

    expect(acquireLockWithConflictDetection("src/index.ts", "T1").success).toBe(true);
    expect(acquireLockWithConflictDetection("src/index.ts", "T2").success).toBe(false); // Already locked by T1
    expect(acquireLockWithConflictDetection("src/index.ts", "T2").conflict).toBe("T1");
    expect(acquireLockWithConflictDetection("src/utils.ts", "T2").success).toBe(true); // Different file
  });

  it("should track task execution state", () => {
    interface TaskState {
      taskId: string;
      status: "pending" | "in_progress" | "completed" | "failed";
      startedAt?: string;
      completedAt?: string;
    }

    const taskStates: Map<string, TaskState> = new Map();

    // Start task
    taskStates.set("T1", { taskId: "T1", status: "in_progress", startedAt: new Date().toISOString() });
    expect(taskStates.get("T1")?.status).toBe("in_progress");

    // Complete task
    const t1 = taskStates.get("T1")!;
    taskStates.set("T1", { ...t1, status: "completed", completedAt: new Date().toISOString() });
    expect(taskStates.get("T1")?.status).toBe("completed");
  });

  it("should respect TDD cycle - test before implementation", () => {
    let redPhaseRan = false;
    let greenPhaseRan = false;

    // RED: Write failing test first
    function writeFailingTest(): void {
      redPhaseRan = true;
      // Test should fail initially
    }

    // GREEN: Write minimal code to pass
    function writeMinimalCode(): void {
      if (!redPhaseRan) throw new Error("Must write test first");
      greenPhaseRan = true;
    }

    // Execute TDD cycle
    writeFailingTest();
    writeMinimalCode();

    expect(redPhaseRan).toBe(true);
    expect(greenPhaseRan).toBe(true);
  });

  it("should release locks after task completion", () => {
    const locks: Set<string> = new Set(["T1:src/index.ts", "T1:src/auth.ts"]);

    function releaseTaskLocks(taskId: string): number {
      let released = 0;
      for (const key of locks) {
        if (key.startsWith(`${taskId}:`)) {
          locks.delete(key);
          released++;
        }
      }
      return released;
    }

    expect(releaseTaskLocks("T1")).toBe(2);
    expect(locks.size).toBe(0);
  });
});

// =============================================================================
// GaoYao Flow Tests  
// =============================================================================

describe("GaoYao - Quality Audit", () => {
  let project: TestProject;
  let ctx: MockContext;

  beforeEach(() => {
    project = createTestProject();
    ctx = createMockContext(project.path);
  });

  afterEach(() => {
    cleanupTestProject(project);
  });

  it("should run quick review for CRITICAL issues only", () => {
    const quickReviewChecks = [
      "syntax_errors",
      "import_errors", 
      "type_errors",
      "security_vulnerabilities_critical"
    ];

    expect(quickReviewChecks).toHaveLength(4);
  });

  it("should run full review for all quality gates", () => {
    const fullReviewChecks = [
      "code_quality",
      "security_vulnerabilities",
      "test_coverage",
      "performance",
      "documentation",
      "style",
      "linting"
    ];

    expect(fullReviewChecks).toHaveLength(7);
  });

  it("should detect security vulnerabilities", () => {
    const vulnerablePatterns = [
      { pattern: "eval(", severity: "critical", reason: "Code injection" },
      { pattern: "SELECT * FROM", severity: "major", reason: "SQL injection risk" },
      { pattern: "password = ", severity: "critical", reason: "Hardcoded credential" },
      { pattern: "exec(", severity: "critical", reason: "Command injection" }
    ];

    const code = "const query = 'SELECT * FROM users'; eval(userInput);";
    
    const detected: string[] = [];
    for (const { pattern } of vulnerablePatterns) {
      if (code.includes(pattern)) {
        detected.push(pattern);
      }
    }

    expect(detected).toContain("SELECT * FROM");
    expect(detected).toContain("eval(");
  });

  it("should return PASS verdict for quality code", () => {
    interface ReviewResult {
      verdict: "PASS" | "NEEDS_CHANGES" | "REJECTED";
      qualityScore: number;
      checks: Record<string, boolean>;
    }

    const cleanCode: ReviewResult = {
      verdict: "PASS",
      qualityScore: 95,
      checks: {
        codeQuality: true,
        security: true,
        testCoverage: true,
        performance: true,
        documentation: true
      }
    };

    expect(cleanCode.verdict).toBe("PASS");
    expect(cleanCode.qualityScore).toBeGreaterThanOrEqual(90);
  });

  it("should return NEEDS_CHANGES for code with issues", () => {
    interface ReviewResult {
      verdict: "PASS" | "NEEDS_CHANGES" | "REJECTED";
      qualityScore: number;
      issues: string[];
    }

    const codeWithIssues: ReviewResult = {
      verdict: "NEEDS_CHANGES",
      qualityScore: 65,
      issues: [
        "Missing error handling in auth.ts",
        "No test coverage for session module",
        "Performance: N+1 query in user lookup"
      ]
    };

    expect(codeWithIssues.verdict).toBe("NEEDS_CHANGES");
    expect(codeWithIssues.issues.length).toBeGreaterThan(0);
  });
});

// =============================================================================
// End-to-End Workflow Tests
// =============================================================================

describe("Four Sages End-to-End Workflow", () => {
  let project: TestProject;
  let ctx: MockContext;

  beforeEach(() => {
    project = createTestProject();
    ctx = createMockContext(project.path);
  });

  afterEach(() => {
    cleanupTestProject(project);
  });

  it("should complete full workflow: Draft → Review → Plan → Execute → Audit", () => {
    // Step 1: Fuxi creates draft
    const draftContent = `# Design Draft: ${project.name}

## ☰ Qian (Heaven) - Core Intent
Build auth system

## ☷ Kun (Earth) - Data Structures
User, Session

## ☳ Zhen (Thunder) - Triggers
Login, logout

## ☴ Xun (Wind) - Flow
User → Auth → JWT

## ☵ Kan (Water) - Error
Handle failures

## ☲ Li (Fire) - Observe
Log events

## ☶ Gen (Mountain) - Bounds
No third-party

## ☱ Dui (Lake) - Success
Login success

## Notes
MVP
`;
    const draftPath = join(project.path, ".sages", "plans", `${project.name}.draft.md`);
    writeFileSync(draftPath, draftContent);
    expect(existsSync(draftPath)).toBe(true);

    // Step 2: QiaoChui decomposes into plan and execution
    const executionContent = `name: ${project.name}

settings:
  maxParallel: 4
  maxFailure: 12
  retryAttempts: 3
  checkpointInterval: 300
  lockTimeout: 1800

phases:
  - name: Phase 1
    parallel: false
    maxParallel: 1
    tasks:
      - id: T1
        description: "Implement User entity"
        agent: luban
        dependsOn: []
        priority: 1
        files: ["src/models/user.ts"]
      - id: T2
        description: "Implement auth service"
        agent: luban
        dependsOn: ["T1"]
        priority: 1
        files: ["src/services/auth.ts"]
`;
    const executionPath = join(project.path, ".sages", "plans", `${project.name}.execution.yaml`);
    writeFileSync(executionPath, executionContent);
    expect(existsSync(executionPath)).toBe(true);

    // Step 3: LuBan executes tasks (simulated)
    const taskResults: Map<string, "completed" | "failed"> = new Map();
    taskResults.set("T1", "completed"); // T1 completed
    taskResults.set("T2", "completed"); // T2 completed

    expect(taskResults.get("T1")).toBe("completed");
    expect(taskResults.get("T2")).toBe("completed");

    // Step 4: GaoYao audits
    const auditResult = {
      verdict: "PASS" as const,
      qualityScore: 92,
      checks: {
        codeQuality: true,
        security: true,
        testCoverage: true,
        performance: true,
        documentation: true
      }
    };

    expect(auditResult.verdict).toBe("PASS");
    expect(auditResult.qualityScore).toBeGreaterThanOrEqual(90);
  });

  it("should handle workflow with task failure and retry", () => {
    const taskStates: Map<string, { status: string; attempts: number }> = new Map();

    // T1 fails first attempt
    taskStates.set("T1", { status: "failed", attempts: 1 });
    expect(taskStates.get("T1")?.attempts).toBe(1);

    // T1 retries and succeeds
    taskStates.set("T1", { status: "completed", attempts: 2 });
    expect(taskStates.get("T1")?.status).toBe("completed");
    expect(taskStates.get("T1")?.attempts).toBe(2);

    // T2 never retries, fails permanently
    taskStates.set("T2", { status: "failed", attempts: 3 }); // max retries reached
    expect(taskStates.get("T2")?.attempts).toBe(3);

    // Circuit breaker threshold
    const maxFailures = 12;
    let failureCount = 0;
    
    for (const [taskId, state] of taskStates) {
      if (state.status === "failed") {
        failureCount++;
      }
    }

    expect(failureCount).toBe(1);
    expect(failureCount < maxFailures).toBe(true); // Circuit stays closed
  });

  it("should open circuit breaker after max failures", () => {
    const maxFailures = 12;
    let failureCount = 0;
    
    // Simulate 13 failures
    for (let i = 0; i < 13; i++) {
      failureCount++;
    }

    const circuitOpen = failureCount >= maxFailures;
    expect(circuitOpen).toBe(true);
  });

  it("should persist checkpoint state for crash recovery", () => {
    interface CheckpointState {
      workflowId: string;
      currentPhase: number;
      currentTaskIndex: number;
      status: string;
      checkpointedAt: string;
    }

    const checkpoint: CheckpointState = {
      workflowId: "wf-123",
      currentPhase: 1,
      currentTaskIndex: 2,
      status: "running",
      checkpointedAt: new Date().toISOString()
    };

    // Save checkpoint to file (simulated)
    const checkpointPath = join(project.path, ".sages", "wf-123.checkpoint.json");
    writeFileSync(checkpointPath, JSON.stringify(checkpoint));

    // Load checkpoint
    const loaded = JSON.parse(readFileSync(checkpointPath, "utf-8")) as CheckpointState;

    expect(loaded.workflowId).toBe("wf-123");
    expect(loaded.currentPhase).toBe(1);
    expect(loaded.currentTaskIndex).toBe(2);
    expect(loaded.status).toBe("running");
  });

  it("should resolve file locks after task completion", () => {
    interface FileLock {
      taskId: string;
      filePath: string;
      lockedAt: string;
      expiresAt: string;
    }

    const locks: Map<string, FileLock> = new Map();
    locks.set("T1:src/index.ts", { taskId: "T1", filePath: "src/index.ts", lockedAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 1800000).toISOString() });
    locks.set("T1:src/auth.ts", { taskId: "T1", filePath: "src/auth.ts", lockedAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 1800000).toISOString() });
    locks.set("T2:src/user.ts", { taskId: "T2", filePath: "src/user.ts", lockedAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 1800000).toISOString() });

    function releaseLocks(taskId: string): void {
      for (const [key, lock] of locks) {
        if (lock.taskId === taskId) {
          locks.delete(key);
        }
      }
    }

    // T1 completes and releases locks
    releaseLocks("T1");
    expect(locks.size).toBe(1);
    expect(locks.has("T1:src/index.ts")).toBe(false);
    expect(locks.has("T2:src/user.ts")).toBe(true);
  });
});

// =============================================================================
// YAML Parser Tests
// =============================================================================

describe("YAML Parser Integration", () => {
  let project: TestProject;

  beforeEach(() => {
    project = createTestProject();
  });

  afterEach(() => {
    cleanupTestProject(project);
  });

  it("should parse execution YAML generated by QiaoChui", () => {
    const executionYaml = `name: test-auth

settings:
  maxParallel: 4
  maxFailure: 12
  retryAttempts: 3
  checkpointInterval: 300
  lockTimeout: 1800

phases:
  - name: Phase 1
    parallel: false
    maxParallel: 1
    tasks:
      - id: T1
        description: "Create User model"
        agent: luban
        dependsOn: []
        priority: 1
        files: ["src/models/user.ts"]
      - id: T2
        description: "Create Session model"
        agent: luban
        dependsOn: ["T1"]
        priority: 1
        files: ["src/models/session.ts"]
`;

    const executionPath = join(project.path, ".sages", "plans", "test-auth.execution.yaml");
    writeFileSync(executionPath, executionYaml);

    expect(existsSync(executionPath)).toBe(true);
    
    // Verify YAML structure
    expect(executionYaml).toContain("name: test-auth");
    expect(executionYaml).toContain("maxParallel: 4");
    expect(executionYaml).toContain("- id: T1");
    expect(executionYaml).toContain("- id: T2");
    expect(executionYaml).toContain('dependsOn: ["T1"]');
  });

  it("should parse high-level workflow YAML (four-sages format)", () => {
    const workflowYaml = `name: fuxi-four-gods
version: 1.0.0

description: Four Sages workflow

phases:
  - name: design
    agent: fuxi
    description: Design phase
    
  - name: review
    agent: qiaochui
    description: Review phase
    
  - name: execute
    agent: luban
    description: Execution phase
    tasks:
      - id: T1
        description: "Implement feature"
        agent: luban
        dependsOn: []
        files: []
`;

    const workflowPath = join(project.path, ".sages", "workflow.yaml");
    writeFileSync(workflowPath, workflowYaml);

    expect(existsSync(workflowPath)).toBe(true);
    
    // Should parse name
    expect(workflowYaml).toContain("name: fuxi-four-gods");
    
    // Should have phases with agents (agent phases without tasks)
    expect(workflowYaml).toContain("agent: fuxi");
    expect(workflowYaml).toContain("agent: qiaochui");
    
    // Should have phase with actual tasks
    expect(workflowYaml).toContain("agent: luban");
    expect(workflowYaml).toContain("- id: T1");
  });

  it("should handle four-sages.yaml with all agent definitions", () => {
    const fourSagesYaml = `name: fuxi-four-gods
version: 1.0.0

settings:
  maxParallel: 4
  maxFailure: 12
  retryAttempts: 3
  checkpointInterval: 300
  lockTimeout: 1800

phases:
  - name: design
    agent: fuxi
    tasks:
      - id: T1
        description: "Create design draft"
        agent: fuxi
        dependsOn: []
        files: []
  - name: review
    agent: qiaochui
    tasks:
      - id: T2
        description: "Review and decompose"
        agent: qiaochui
        dependsOn: ["T1"]
        files: []
  - name: execute
    agent: luban
    tasks:
      - id: T3
        description: "Implement task"
        agent: luban
        dependsOn: ["T2"]
        files: []
  - name: audit
    agent: gaoyao
    tasks:
      - id: T4
        description: "Quality audit"
        agent: gaoyao
        dependsOn: ["T3"]
        files: []

agents:
  fuxi:
    name: Fuxi (伏羲)
    role: Architect
  qiaochui:
    name: QiaoChui (巧倕)
    role: Divine Mechanist
  luban:
    name: LuBan (鲁班)
    role: Master Craftsman
  gaoyao:
    name: GaoYao (皋陶)
    role: Supreme Judge
`;

    const path = join(project.path, ".sages", "four-sages.yaml");
    writeFileSync(path, fourSagesYaml);

    expect(existsSync(path)).toBe(true);
    
    // Verify phases with tasks are preserved
    expect(fourSagesYaml).toContain("- id: T1");
    expect(fourSagesYaml).toContain("- id: T2");
    expect(fourSagesYaml).toContain("- id: T3");
    expect(fourSagesYaml).toContain("- id: T4");
    
    // Verify agent definitions are preserved
    expect(fourSagesYaml).toContain("agents:");
    expect(fourSagesYaml).toContain("fuxi:");
    expect(fourSagesYaml).toContain("qiaochui:");
    expect(fourSagesYaml).toContain("luban:");
    expect(fourSagesYaml).toContain("gaoyao:");
  });
});
