/**
 * Unit Tests for Fuxi Tools
 * Tests draft creation, parsing, completeness validation, and fuxi_get_status
 */
import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { mkdirSync, rmSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { parseDraft, isDraftComplete, type ParsedDraft } from "../../src/utils/parseDraft";
import { fuxi_get_status, fuxi_resume, fuxi_generate_report, fuxi_transition_phase } from "../../src/tools/fuxi-tools";
import type { PluginContext } from "../../src/types";

// Import the tool's execute function directly for testing
const fuxiGetStatusExecute = fuxi_get_status.execute;
const fuxiResumeExecute = fuxi_resume.execute;
const fuxiGenerateReportExecute = fuxi_generate_report.execute;
const fuxiTransitionPhaseExecute = fuxi_transition_phase.execute;

describe("Fuxi Tools - Draft Parsing", () => {
  describe("parseDraft", () => {
    it("should parse a complete draft with all 8 trigrams", () => {
      const content = `# Design Draft: test-project

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Build a user authentication system

## ☷ Kun (Earth) - Data Structures

- User entity with id, email, password
- Session entity with token and expiry

## ☳ Zhen (Thunder) - Trigger Mechanisms

- User login event triggers session creation
- Logout event triggers session deletion

## ☴ Xun (Wind) - Data Flow

User → API → Auth Service → Database

## ☵ Kan (Water) - Error Handling

- Invalid credentials return 401
- Database errors return 500 with retry

## ☲ Li (Fire) - Observability

- Log all authentication attempts
- Track session creation/deletion metrics

## ☶ Gen (Mountain) - Boundary Constraints

- Do not store passwords in plain text
- Do not allow session tokens in URL parameters

## ☱ Dui (Lake) - Success Path

1. User submits credentials
2. System validates against database
3. Session created and token returned
4. User authenticated for subsequent requests

## Notes

This is a test implementation`;

      const result = parseDraft(content);

      expect(result).not.toBeNull();
      expect(result!.name).toBe("test-project");
      expect(result!.timestamp).toBe("2026-04-26T10:00:00.000Z");
      expect(result!.status).toBe("draft");
      expect(result!.sections.qian).toContain("Build a user authentication system");
      expect(result!.sections.kun).toContain("User entity");
      expect(result!.sections.dui).toContain("User submits credentials");
      expect(result!.notes).toBe("This is a test implementation");
    });

    it("should parse draft with only some sections filled", () => {
      const content = `# Design Draft: partial

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Simple task

## ☷ Kun (Earth) - Data Structures

{Define core entities}

## ☴ Xun (Wind) - Data Flow

{Define how data flows}

## Notes

Needs more work`;

      const result = parseDraft(content);

      expect(result).not.toBeNull();
      expect(result!.name).toBe("partial");
      expect(result!.sections.qian).toContain("Simple task");
      expect(result!.sections.kun).toContain("{Define core entities}"); // placeholder text is parsed
    });

    it("should return empty object for invalid content", () => {
      const result = parseDraft("not a valid draft");
      // parseDraft doesn't throw, returns empty parsed object with empty values
      expect(result).not.toBeNull();
      expect(result!.name).toBe("");
    });

    it("should handle empty content", () => {
      const result = parseDraft("");
      // parseDraft doesn't throw, returns empty parsed object
      expect(result).not.toBeNull();
      expect(result!.sections).toEqual({});
    });

    it("should parse sections with emoji headers", () => {
      const content = `# Design Draft: emoji-test

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Test content`;

      const result = parseDraft(content);

      expect(result).not.toBeNull();
      expect(result!.sections.qian).toBe("Test content\n");
    });
  });

  describe("isDraftComplete", () => {
    it("should return true for drafts with 5+ filled sections", () => {
      const draft: ParsedDraft = {
        name: "test",
        timestamp: "2026-04-26T10:00:00.000Z",
        status: "draft",
        sections: {
          qian: "Core intent content here",
          kun: "Data structures content here",
          zhen: "Triggers content here",
          xun: "Data flow content here",
          kan: "Error handling content here",
        },
      };

      expect(isDraftComplete(draft)).toBe(true);
    });

    it("should return false for drafts with less than 5 filled sections", () => {
      const draft: ParsedDraft = {
        name: "test",
        timestamp: "2026-04-26T10:00:00.000Z",
        status: "draft",
        sections: {
          qian: "Core intent content here",
          kun: "Data structures content here",
        },
      };

      expect(isDraftComplete(draft)).toBe(false);
    });

    it("should return false for empty sections", () => {
      const draft: ParsedDraft = {
        name: "test",
        timestamp: "2026-04-26T10:00:00.000Z",
        status: "draft",
        sections: {
          qian: "",
          kun: "Data structures",
        },
      };

      expect(isDraftComplete(draft)).toBe(false);
    });

    it("should return false for sections with placeholder text", () => {
      const draft: ParsedDraft = {
        name: "test",
        timestamp: "2026-04-26T10:00:00.000Z",
        status: "draft",
        sections: {
          qian: "{Define core intent}",
          kun: "Data structures",
          zhen: "Triggers",
          xun: "Data flow",
          kan: "Error handling",
        },
      };

      // Placeholder text is only 16 chars, threshold is 10
      expect(isDraftComplete(draft)).toBe(false);
    });

    it("should return false for empty sections object", () => {
      const draft: ParsedDraft = {
        name: "test",
        timestamp: "2026-04-26T10:00:00.000Z",
        status: "draft",
        sections: {},
      };

      expect(isDraftComplete(draft)).toBe(false);
    });
  });
});

describe("fuxi_get_status", () => {
  const TEST_DIR = join(tmpdir(), "sages-fuxi-get-status-test-" + Date.now());
  const planName = "test-plan";

  // Mock context for tool execution
  const mockCtx: PluginContext = {
    sessionID: "test-session",
    messageID: "test-message",
    agent: TEST_DIR,
  };

  beforeEach(() => {
    mkdirSync(TEST_DIR, { recursive: true });
  });

  afterEach(() => {
    try {
      rmSync(TEST_DIR, { recursive: true, force: true });
    } catch {
      // ignore cleanup errors
    }
  });

  describe("state file reading", () => {
    it("should read state file from .plan/{name}/state.json", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName,
        status: "execution",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "implementation",
        completedTasks: 3,
        totalTasks: 10,
        nextTask: "T4",
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiGetStatusExecute({ name: planName }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(true);
      expect(parsed.data.planName).toBe("test-plan");
      expect(parsed.data.currentPhase).toBe("implementation");
      expect(parsed.data.completedTasks).toBe(3);
      expect(parsed.data.totalTasks).toBe(10);
      expect(parsed.data.nextTask).toBe("T4");
      expect(parsed.data.status).toBe("execution");
    });

    it("should return error when state file does not exist", async () => {
      const result = await fuxiGetStatusExecute({ name: "nonexistent" }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(false);
      expect(parsed.error.message).toContain("State file not found");
    });

    it("should return all required state fields", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "complete-state-test",
        status: "execution",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "phase-1",
        completedTasks: 5,
        totalTasks: 8,
        nextTask: "T6",
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiGetStatusExecute({ name: planName }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(true);
      expect(parsed.data).toHaveProperty("currentPhase");
      expect(parsed.data).toHaveProperty("completedTasks");
      expect(parsed.data).toHaveProperty("totalTasks");
      expect(parsed.data).toHaveProperty("nextTask");
      expect(parsed.data).toHaveProperty("status");
      expect(parsed.data).toHaveProperty("planName");
    });

    it("should handle state with no nextTask (all complete)", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "completed-plan",
        status: "completed",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "final-phase",
        completedTasks: 10,
        totalTasks: 10,
        nextTask: undefined,
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiGetStatusExecute({ name: planName }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(true);
      expect(parsed.data.completedTasks).toBe(parsed.data.totalTasks);
      expect(parsed.data.nextTask).toBeUndefined();
      expect(parsed.data.status).toBe("completed");
    });
  });
});

describe("fuxi_resume", () => {
  const TEST_DIR = join(tmpdir(), "sages-fuxi-resume-test-" + Date.now());
  const planName = "test-plan";

  // Mock context for tool execution
  const mockCtx: PluginContext = {
    sessionID: "test-session",
    messageID: "test-message",
    agent: TEST_DIR,
  };

  beforeEach(() => {
    mkdirSync(TEST_DIR, { recursive: true });
  });

  afterEach(() => {
    try {
      rmSync(TEST_DIR, { recursive: true, force: true });
    } catch {
      // ignore cleanup errors
    }
  });

  describe("error cases", () => {
    it("should return error when state file does not exist", async () => {
      const result = await fuxiResumeExecute({ name: "nonexistent" }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(false);
      expect(parsed.error.message).toContain("State file not found");
    });

    it("should return error when workflow already completed", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "completed-plan",
        status: "completed",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "final-phase",
        completedTasks: 10,
        totalTasks: 10,
        nextTask: undefined,
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiResumeExecute({ name: planName }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(false);
      expect(parsed.error.message).toContain("already completed");
    });

    it("should return error when workflow failed", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "failed-plan",
        status: "failed",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "implementation",
        completedTasks: 3,
        totalTasks: 10,
        nextTask: "T4",
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiResumeExecute({ name: planName }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(false);
      expect(parsed.error.message).toContain("failed");
    });

    it("should return error when no incomplete task found", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "no-task-plan",
        status: "execution",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "implementation",
        completedTasks: 10,
        totalTasks: 10,
        nextTask: undefined,
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiResumeExecute({ name: planName }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(false);
      expect(parsed.error.message).toContain("No incomplete task");
    });
  });

  describe("resumption logic", () => {
    it("should resume from next incomplete task", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "test-plan",
        status: "execution",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "implementation",
        completedTasks: 3,
        totalTasks: 10,
        nextTask: "T4",
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiResumeExecute({ name: planName }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(true);
      expect(parsed.data.planName).toBe("test-plan");
      expect(parsed.data.resumedFromTask).toBe("T4");
      expect(parsed.data.completedTasks).toBe(3);
      expect(parsed.data.totalTasks).toBe(10);
      expect(parsed.data.status).toBe("execution");
    });

    it("should update state file on resumption", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "test-plan",
        status: "execution",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "implementation",
        completedTasks: 3,
        totalTasks: 10,
        nextTask: "T4",
      };
      writeFileSync(stateFile, JSON.stringify(state));

      await fuxiResumeExecute({ name: planName }, mockCtx);

      // Verify state file was updated
      const updatedState = JSON.parse(readFileSync(stateFile, "utf-8"));
      expect(updatedState.lastResumedAt).toBeDefined();
    });
  });
});

describe("fuxi_generate_report", () => {
  const TEST_DIR = join(tmpdir(), "sages-fuxi-generate-report-test-" + Date.now());
  const planName = "test-plan";

  // Mock context for tool execution
  const mockCtx: PluginContext = {
    sessionID: "test-session",
    messageID: "test-message",
    agent: TEST_DIR,
  };

  beforeEach(() => {
    mkdirSync(TEST_DIR, { recursive: true });
  });

  afterEach(() => {
    try {
      rmSync(TEST_DIR, { recursive: true, force: true });
    } catch {
      // ignore cleanup errors
    }
  });

  describe("error cases", () => {
    it("should return error when state file does not exist", async () => {
      const result = await fuxiGenerateReportExecute({ name: "nonexistent" }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(false);
      expect(parsed.error.message).toContain("State file not found");
    });
  });

  describe("report generation", () => {
    it("should generate report with completion rate", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "test-plan",
        status: "completed",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "audit",
        completedTasks: 8,
        totalTasks: 10,
        nextTask: undefined,
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiGenerateReportExecute({ name: planName }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(true);
      expect(parsed.data.planName).toBe("test-plan");
      expect(parsed.data.completionRate).toBe("80%");
      expect(parsed.data.completedTasks).toBe(8);
      expect(parsed.data.totalTasks).toBe(10);
    });

    it("should generate report with overall status", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "status-test-plan",
        status: "execution",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "implementation",
        completedTasks: 3,
        totalTasks: 10,
        nextTask: "T4",
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiGenerateReportExecute({ name: planName }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(true);
      expect(parsed.data.overallStatus).toBe("execution");
      expect(parsed.data.currentPhase).toBe("implementation");
    });

    it("should identify no errors when workflow is successful", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "success-plan",
        status: "completed",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "audit",
        completedTasks: 10,
        totalTasks: 10,
        nextTask: undefined,
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiGenerateReportExecute({ name: planName }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(true);
      expect(parsed.data.errorsEncountered).toBeUndefined();
    });

    it("should identify errors when workflow failed", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "failed-plan",
        status: "failed",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "implementation",
        completedTasks: 3,
        totalTasks: 10,
        nextTask: "T4",
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiGenerateReportExecute({ name: planName }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(true);
      expect(parsed.data.errorsEncountered).toEqual(["Workflow failed"]);
    });

    it("should recommend investigation when workflow failed", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "failed-plan",
        status: "failed",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "implementation",
        completedTasks: 3,
        totalTasks: 10,
        nextTask: "T4",
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiGenerateReportExecute({ name: planName }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(true);
      expect(parsed.data.recommendations).toContain("Investigate and fix the failed workflow");
    });

    it("should generate 100% completion report for fully completed workflow", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "full-completion-plan",
        status: "completed",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "audit",
        completedTasks: 5,
        totalTasks: 5,
        nextTask: undefined,
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiGenerateReportExecute({ name: planName }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(true);
      expect(parsed.data.completionRate).toBe("100%");
      expect(parsed.data.recommendations).toContain("Workflow completed successfully");
    });
  });
});

describe("fuxi_transition_phase", () => {
  const TEST_DIR = join(tmpdir(), "sages-fuxi-transition-phase-test-" + Date.now());
  const planName = "test-plan";

  // Mock context for tool execution
  const mockCtx: PluginContext = {
    sessionID: "test-session",
    messageID: "test-message",
    agent: TEST_DIR,
  };

  beforeEach(() => {
    mkdirSync(TEST_DIR, { recursive: true });
  });

  afterEach(() => {
    try {
      rmSync(TEST_DIR, { recursive: true, force: true });
    } catch {
      // ignore cleanup errors
    }
  });

  describe("error cases", () => {
    it("should return error when state file does not exist", async () => {
      const result = await fuxiTransitionPhaseExecute({ name: "nonexistent", new_phase: "implementation" }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(false);
      expect(parsed.error.message).toContain("State file not found");
    });

    it("should return error when new_phase is empty", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "test-plan",
        status: "execution",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "implementation",
        completedTasks: 5,
        totalTasks: 10,
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiTransitionPhaseExecute({ name: planName, new_phase: "" }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(false);
      expect(parsed.error.message).toContain("new_phase cannot be empty");
    });

    it("should return error when workflow is not in execution state", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      // Create state with idle status (no actual workflow started)
      const state = {
        planName: "idle-plan",
        status: "idle",
        hasDraft: false,
        hasPlan: false,
        hasExecution: false,
        completedTasks: 0,
        totalTasks: 0,
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiTransitionPhaseExecute({ name: planName, new_phase: "implementation" }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(false);
      expect(parsed.error.message).toContain("not in execution");
    });

    it("should return error when workflow is completed", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "completed-plan",
        status: "completed",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "audit",
        completedTasks: 10,
        totalTasks: 10,
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiTransitionPhaseExecute({ name: planName, new_phase: "next-phase" }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(false);
      expect(parsed.error.message).toContain("completed");
    });

    it("should return error when workflow has failed", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "failed-plan",
        status: "failed",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "implementation",
        completedTasks: 3,
        totalTasks: 10,
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiTransitionPhaseExecute({ name: planName, new_phase: "next-phase" }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(false);
      expect(parsed.error.message).toContain("failed");
    });

    it("should return error when workflow is in audit state", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "audit-plan",
        status: "audit",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "audit",
        completedTasks: 8,
        totalTasks: 10,
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiTransitionPhaseExecute({ name: planName, new_phase: "remediation" }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(false);
      expect(parsed.error.message).toContain("not in execution");
    });
  });

  describe("successful phase transition", () => {
    it("should transition to a new phase", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "test-plan",
        status: "execution",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "implementation",
        completedTasks: 5,
        totalTasks: 10,
        nextTask: "T6",
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiTransitionPhaseExecute({ name: planName, new_phase: "testing" }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(true);
      expect(parsed.data.previousPhase).toBe("implementation");
      expect(parsed.data.newPhase).toBe("testing");
      expect(parsed.data.planName).toBe("test-plan");
    });

    it("should update the state file with new phase", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "test-plan",
        status: "execution",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "implementation",
        completedTasks: 5,
        totalTasks: 10,
        nextTask: "T6",
      };
      writeFileSync(stateFile, JSON.stringify(state));

      await fuxiTransitionPhaseExecute({ name: planName, new_phase: "testing" }, mockCtx);

      // Verify state file was updated
      const updatedState = JSON.parse(readFileSync(stateFile, "utf-8"));
      expect(updatedState.currentPhase).toBe("testing");
    });

    it("should return transition details in response", async () => {
      const stateFile = join(TEST_DIR, ".plan", planName, "state.json");
      mkdirSync(join(TEST_DIR, ".plan", planName), { recursive: true });

      const state = {
        planName: "transition-details-test",
        status: "execution",
        hasDraft: true,
        hasPlan: true,
        hasExecution: true,
        currentPhase: "phase-1",
        completedTasks: 2,
        totalTasks: 8,
        nextTask: "T3",
      };
      writeFileSync(stateFile, JSON.stringify(state));

      const result = await fuxiTransitionPhaseExecute({ name: planName, new_phase: "phase-2" }, mockCtx);
      const parsed = JSON.parse(result);

      expect(parsed.success).toBe(true);
      expect(parsed.data).toHaveProperty("previousPhase");
      expect(parsed.data).toHaveProperty("newPhase");
      expect(parsed.data).toHaveProperty("planName");
      expect(parsed.data.previousPhase).toBe("phase-1");
      expect(parsed.data.newPhase).toBe("phase-2");
    });
  });
});
