/**
 * Unit Tests for QiaoChui Tools
 * Tests review and decomposition logic
 */
import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { mkdirSync, rmSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";

// Helper to create temp project structure
function createTempProject(): string {
  const tempDir = join("/tmp", `qiaochui-test-${Date.now()}`);
  mkdirSync(tempDir, { recursive: true });
  mkdirSync(join(tempDir, ".sages", "plans"), { recursive: true });
  return tempDir;
}

// Helper to cleanup temp project
function cleanupTempProject(tempDir: string): void {
  rmSync(tempDir, { recursive: true, force: true });
}

// Mock the parseDraft function for testing
function parseDraftForTest(content: string): { sections: Record<string, string>; notes?: string } | null {
  try {
    const lines = content.split("\n");
    const sections: Record<string, string> = {};
    let currentSection = "";

    for (const line of lines) {
      if (line.startsWith("## ☰ Qian")) currentSection = "qian";
      else if (line.startsWith("## ☷ Kun")) currentSection = "kun";
      else if (line.startsWith("## ☳ Zhen")) currentSection = "zhen";
      else if (line.startsWith("## ☴ Xun")) currentSection = "xun";
      else if (line.startsWith("## ☵ Kan")) currentSection = "kan";
      else if (line.startsWith("## ☲ Li")) currentSection = "li";
      else if (line.startsWith("## ☶ Gen")) currentSection = "gen";
      else if (line.startsWith("## ☱ Dui")) currentSection = "dui";
      else if (line.startsWith("## Notes")) currentSection = "notes";
      else if (currentSection && line.trim()) {
        sections[currentSection] = (sections[currentSection] || "") + line + "\n";
      }
    }

    return { sections, notes: sections.notes };
  } catch {
    return null;
  }
}

function isDraftCompleteForTest(parsed: { sections: Record<string, string> } | null): boolean {
  if (!parsed) return false;
  const sectionCount = Object.values(parsed.sections).filter((s) => s && s.trim().length > 10).length;
  return sectionCount >= 5;
}

describe("QiaoChui Tools - Review Logic", () => {
  describe("Draft Completeness Check", () => {
    it("should approve complete draft (5+ sections filled)", () => {
      const content = `# Design Draft: test

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Build a web application with user authentication

## ☷ Kun (Earth) - Data Structures

- User: id, email, password_hash, created_at
- Session: id, user_id, token, expires_at

## ☳ Zhen (Thunder) - Trigger Mechanisms

- Login event creates session
- Logout event destroys session

## ☴ Xun (Wind) - Data Flow

Browser → API Gateway → Auth Service → Database

## ☵ Kan (Water) - Error Handling

- 401 for invalid credentials
- 500 for database errors with retry logic

## ☲ Li (Fire) - Observability

- Log all auth attempts to file
- Track metrics with timestamps

## ☶ Gen (Mountain) - Boundary Constraints

- Never log passwords
- Never expose tokens in URLs

## ☱ Dui (Lake) - Success Path

1. User POSTs credentials
2. System validates
3. Session created
4. Token returned in response</text>`;

      const parsed = parseDraftForTest(content);
      expect(isDraftCompleteForTest(parsed)).toBe(true);
    });

    it("should reject incomplete draft (less than 5 sections)", () => {
      const content = `# Design Draft: incomplete

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Build something

## ☷ Kun (Earth) - Data Structures

User entity</text>`;

      const parsed = parseDraftForTest(content);
      expect(isDraftCompleteForTest(parsed)).toBe(false);
    });

    it("should detect placeholder text", () => {
      const content = `# Design Draft: placeholder

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

TBD

## ☷ Kun (Earth) - Data Structures

TBD

## ☳ Zhen (Thunder) - Trigger Mechanisms

TBD

## ☴ Xun (Wind) - Data Flow

TBD

## ☵ Kan (Water) - Error Handling

TBD

## ☲ Li (Fire) - Observability

TBD</text>`;

      const parsed = parseDraftForTest(content);
      expect(isDraftCompleteForTest(parsed)).toBe(false);

      // Check for placeholders (TBD text)
      const hasPlaceholders = Object.values(parsed?.sections || {}).some(
        (s) => s && (s.includes("TBD") || s.includes("{")),
      );
      expect(hasPlaceholders).toBe(true);
    });
  });

  describe("Review Verdict Logic", () => {
    it("should return REVISE for incomplete draft", () => {
      const parsed = parseDraftForTest("# Design Draft: test\n\n## ☰ Qian\n\nabc");
      const isComplete = isDraftCompleteForTest(parsed);
      const verdict = isComplete ? "APPROVED" : "REVISE";
      expect(verdict).toBe("REVISE");
    });

    it("should return REVISE for draft with placeholders", () => {
      const content = `# Design Draft: test

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Build a system with proper security

## ☷ Kun (Earth) - Data Structures

User entity with fields

## ☳ Zhen (Thunder) - Trigger Mechanisms

Login creates session

## ☴ Xun (Wind) - Data Flow

Data flows through system

## ☵ Kan (Water) - Error Handling

Handle errors gracefully

## ☲ Li (Fire) - Observability

Log all operations

## ☶ Gen (Mountain) - Boundary Constraints

{Define boundaries}

## ☱ Dui (Lake) - Success Path

User logs in successfully</text>`;

      const parsed = parseDraftForTest(content);
      const hasPlaceholders = Object.values(parsed?.sections || {}).some(
        (s) => s && (s.includes("{") || s.includes("}")),
      );
      expect(hasPlaceholders).toBe(true);
    });

    it("should return APPROVED for complete draft without placeholders", () => {
      const content = `# Design Draft: test

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Build a secure authentication system

## ☷ Kun (Earth) - Data Structures

User: id, email, password_hash, created_at
Session: id, user_id, token, expires_at

## ☳ Zhen (Thunder) - Trigger Mechanisms

Login event creates session
Logout event destroys session
Token refresh extends session

## ☴ Xun (Wind) - Data Flow

Client → API → Auth Service → Database
Auth Service validates credentials
Database returns user record

## ☵ Kan (Water) - Error Handling

Invalid credentials return 401 Unauthorized
Database errors return 500 with exponential backoff
Network timeouts retry up to 3 times

## ☲ Li (Fire) - Observability

All auth attempts logged with timestamp
Session creation/destruction tracked
Failed login attempts alert security team

## ☶ Gen (Mountain) - Boundary Constraints

Never store plain text passwords
Never log sensitive credentials
Never expose tokens in URL parameters
Never allow cross-origin requests without CORS

## ☱ Dui (Lake) - Success Path

1. User submits email and password
2. System validates credentials against database
3. Session created with secure token
4. Token returned in HTTP-only cookie
5. User authenticated for subsequent requests</text>`;

      const parsed = parseDraftForTest(content);
      const isComplete = isDraftCompleteForTest(parsed);
      const hasPlaceholders = Object.values(parsed?.sections || {}).some(
        (s) => s && (s.includes("{") || s.includes("}")),
      );

      expect(isComplete).toBe(true);
      expect(hasPlaceholders).toBe(false);
    });
  });

  describe("Task Decomposition", () => {
    it("should generate correct number of tasks", () => {
      const maxTasks = 5;
      expect(maxTasks).toBe(5);
    });

    it("should include dependencies in task structure", () => {
      const tasks = [
        { id: "T1", description: "Setup project structure", priority: "high", time: 5, depends: [] },
        { id: "T2", description: "Create database schema", priority: "high", time: 10, depends: ["T1"] },
        { id: "T3", description: "Implement auth service", priority: "high", time: 15, depends: ["T1", "T2"] },
        { id: "T4", description: "Add session management", priority: "medium", time: 10, depends: ["T2"] },
        { id: "T5", description: "Write integration tests", priority: "medium", time: 10, depends: ["T3", "T4"] },
      ];

      // T1 has no dependencies
      expect(tasks[0].depends).toEqual([]);

      // T2 depends on T1
      expect(tasks[1].depends).toEqual(["T1"]);

      // T3 depends on T1 and T2
      expect(tasks[2].depends).toEqual(["T1", "T2"]);

      // T4 depends on T2
      expect(tasks[3].depends).toEqual(["T2"]);

      // T5 depends on T3 and T4
      expect(tasks[4].depends).toEqual(["T3", "T4"]);
    });

    it("should calculate total estimated time correctly", () => {
      const tasks = [
        { time: 5 },
        { time: 10 },
        { time: 15 },
        { time: 10 },
        { time: 10 },
      ];

      const totalTime = tasks.reduce((sum, t) => sum + t.time, 0);
      expect(totalTime).toBe(50);
    });
  });

  describe("File Path Handling - Regression Test", () => {
    // This test catches the bug where draft_path.replace(".draft.md", "")
    // incorrectly creates nested directories like:
    //   .sages/plans/test/.sages/plans/test.plan.md
    // instead of:
    //   .sages/plans/test.plan.md

    it("should extract plan name from draft path correctly", () => {
      // Simulate the bug: draft_path.replace(".draft.md", "") on a path
      const draftPath1 = ".sages/plans/my-project.draft.md";
      const planName1 = draftPath1.replace(".draft.md", ""); // ".sages/plans/my-project"
      expect(planName1).toBe(".sages/plans/my-project");

      // The ensurePlanDir function creates a directory at this path
      // Then the plan file is created at: planDir + ".plan.md"
      // This creates: .sages/plans/my-project.plan.md (correct)

      // Bug case: if draftPath already contains .sages/plans prefix in name
      const draftPath2 = ".sages/plans/nested.draft.md";
      const planName2 = draftPath2.replace(".draft.md", ""); // ".sages/plans/nested"
      expect(planName2).toBe(".sages/plans/nested");

      // The correct plan file path should be:
      // .sages/plans/nested.plan.md
      const correctPlanFilePath = planName2 + ".plan.md";
      expect(correctPlanFilePath).toBe(".sages/plans/nested.plan.md");
    });

    it("should NOT create nested .sages directories", () => {
      const tempDir = createTempProject();
      const planName = "test-plan";
      const planDir = join(tempDir, ".sages", "plans", planName);
      const planFilePath = join(planDir, planName + ".plan.md");

      try {
        // Create the plan directory
        mkdirSync(planDir, { recursive: true });

        // Write a plan file
        writeFileSync(planFilePath, "# Test Plan\n\nTasks: []");

        // Verify the structure is correct (NOT nested)
        const expectedPath = join(tempDir, ".sages", "plans", planName, planName + ".plan.md");
        expect(existsSync(expectedPath)).toBe(true);

        // Verify we DON'T have the buggy nested structure
        const buggyPath = join(tempDir, ".sages", "plans", planName, ".sages", "plans", planName + ".plan.md");
        expect(existsSync(buggyPath)).toBe(false);

        // Verify the plan file is directly under .sages/plans/{name}/
        expect(planFilePath).toBe(expectedPath);
      } finally {
        cleanupTempProject(tempDir);
      }
    });

    it("should handle draft paths with various naming patterns", () => {
      const testCases = [
        {
          draftPath: ".sages/plans/my-project.draft.md",
          expectedPlanDir: ".sages/plans/my-project",
          expectedPlanFile: ".sages/plans/my-project.plan.md",
        },
        {
          draftPath: ".sages/plans/another-test.draft.md",
          expectedPlanDir: ".sages/plans/another-test",
          expectedPlanFile: ".sages/plans/another-test.plan.md",
        },
      ];

      for (const tc of testCases) {
        const planName = tc.draftPath.replace(".draft.md", "");
        const planFile = planName + ".plan.md";

        expect(planName).toBe(tc.expectedPlanDir);
        expect(planFile).toBe(tc.expectedPlanFile);
      }
    });

    it("should create plan directory at correct depth", () => {
      const tempDir = createTempProject();
      const projectName = "my-awesome-project";

      // Simulate ensurePlanDir behavior
      const planDir = join(tempDir, ".sages", "plans", projectName);
      const planFile = join(planDir, projectName + ".plan.md");
      const executionFile = join(planDir, projectName + ".execution.yaml");

      try {
        mkdirSync(planDir, { recursive: true });
        writeFileSync(planFile, "# Plan");
        writeFileSync(executionFile, "tasks: []");

        // Verify files exist at correct depth
        expect(existsSync(planFile)).toBe(true);
        expect(existsSync(executionFile)).toBe(true);

        // Verify depth is 4 levels: /tmp/xxx/.sages/plans/my-awesome-project/
        const expectedDepth = planDir.split("/").length;
        expect(expectedDepth).toBeGreaterThan(4);

        // Verify NO extra .sages in the path
        const pathParts = planDir.split("/");
        const sagesCount = pathParts.filter(p => p === ".sages").length;
        expect(sagesCount).toBe(1); // Only one .sages directory
      } finally {
        cleanupTempProject(tempDir);
      }
    });

    it("should correctly derive project dir from draft path", () => {
      // This is the CORE bug: ensurePlanDir appends PLANS_DIR to whatever path it receives.
      // If you pass ".sages/plans/my-project" to ensurePlanDir, it returns
      // ".sages/plans/my-project/.sages/plans" (WRONG!)
      //
      // The correct approach: derive project root from draft path, not plan name
      //
      // Bug: draft_path = ".sages/plans/my-project.draft.md"
      //      draft_path.replace(".draft.md", "") = ".sages/plans/my-project"
      //      ensurePlanDir(".sages/plans/my-project") -> ".sages/plans/my-project/.sages/plans" (WRONG!)
      //
      // Fix: The draft_path should be converted to project dir differently

      const tempDir = createTempProject();
      const planName = "test-project";

      try {
        // Simulate the BUGGY behavior
        const buggyPlanName = join(tempDir, ".sages", "plans", planName);
        const buggyPlanDir = join(buggyPlanName, ".sages", "plans"); // This is what ensurePlanDir would create
        const buggyPlanFile = join(buggyPlanDir, planName + ".plan.md");

        mkdirSync(buggyPlanDir, { recursive: true });
        writeFileSync(buggyPlanFile, "buggy content");

        // The BUG creates a nested .sages/plans inside the plan name directory
        expect(existsSync(buggyPlanFile)).toBe(true);

        // Verify the buggy path has TWO .sages directories
        const buggyParts = buggyPlanFile.split("/");
        const sagesInBuggy = buggyParts.filter(p => p === ".sages").length;
        expect(sagesInBuggy).toBe(2); // BUG: has nested .sages

        // Now verify the CORRECT behavior
        const correctPlanDir = join(tempDir, ".sages", "plans", planName);
        const correctPlanFile = join(correctPlanDir, planName + ".plan.md");

        mkdirSync(correctPlanDir, { recursive: true });
        writeFileSync(correctPlanFile, "correct content");

        // The CORRECT path should have only ONE .sages
        const correctParts = correctPlanFile.split("/");
        const sagesInCorrect = correctParts.filter(p => p === ".sages").length;
        expect(sagesInCorrect).toBe(1);

        // They should be different paths
        expect(buggyPlanFile).not.toBe(correctPlanFile);
      } finally {
        cleanupTempProject(tempDir);
      }
    });
  });
});

describe("QiaoChui Tools - qiaochui_decompose Path Resolution", () => {
  // Import the actual tool
  const { qiaochui_decompose } = require("../../src/tools/qiaochui-tools");

  const testProjectDir = "/tmp/qiaochui-decompose-test";

  beforeEach(() => {
    // Create temp project directory with .sages/plans structure
    mkdirSync(join(testProjectDir, ".sages", "plans"), { recursive: true });
  });

  afterEach(() => {
    if (existsSync(testProjectDir)) {
      rmSync(testProjectDir, { recursive: true, force: true });
    }
  });

  describe("Plan file path resolution", () => {
    it("should create plan and execution files at same level as draft (using dirname)", () => {
      // This is the core test for the dirname() fix
      // Draft: .sages/plans/my-project.draft.md
      // Expected plan: .sages/plans/my-project.plan.md (NOT .sages/plans/my-project/.sages/plans/my-project.plan.md)

      const draftPath = join(testProjectDir, ".sages", "plans", "my-project.draft.md");
      const draftContent = `# Design Draft: my-project

Generated by: Fuxi
Timestamp: 2026-04-27T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Build a feature

## ☷ Kun (Earth) - Data Structures

Entity: id, name

## ☳ Zhen (Thunder) - Trigger Mechanisms

Action triggers event

## ☴ Xun (Wind) - Data Flow

Data flows here

## ☵ Kan (Water) - Error Handling

Handle errors

## ☲ Li (Fire) - Observability

Log operations

## ☶ Gen (Mountain) - Boundary Constraints

No constraints

## ☱ Dui (Lake) - Success Path

Success flow</text>`;

      writeFileSync(draftPath, draftContent);

      // Verify draft exists
      expect(existsSync(draftPath)).toBe(true);

      // Compute expected paths using dirname (the fix)
      const planDir = dirname(draftPath);
      const baseName = "my-project";
      const expectedPlanPath = join(planDir, `${baseName}.plan.md`);
      const expectedExecutionPath = join(planDir, `${baseName}.execution.yaml`);

      // The plan directory should be ".sages/plans" (parent of draft)
      expect(planDir).toBe(join(testProjectDir, ".sages", "plans"));

      // Plan file should be directly in .sages/plans, NOT in .sages/plans/my-project/.sages/plans/
      expect(expectedPlanPath).toBe(join(testProjectDir, ".sages", "plans", "my-project.plan.md"));

      // Verify there is NO nested .sages in the expected path
      const planPathParts = expectedPlanPath.split("/");
      const nestedSagesCount = planPathParts.filter(p => p === ".sages").length;
      expect(nestedSagesCount).toBe(1); // Only one .sages directory
    });

    it("should not create nested .sages/plans structure when using dirname", () => {
      // This test verifies the BUG is fixed: dirname(draft_path) gives correct parent
      // Bug would produce: .sages/plans/my-project/.sages/plans (WRONG)
      // Correct produces: .sages/plans (RIGHT)

      const draftPath = join(testProjectDir, ".sages", "plans", "test-project.draft.md");

      // Create a minimal draft
      writeFileSync(draftPath, `# Design Draft: test-project

Generated by: Fuxi
Timestamp: 2026-04-27T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Test

## ☷ Kun (Earth) - Data Structures

Test

## ☳ Zhen (Thunder) - Trigger Mechanisms

Test

## ☴ Xun (Wind) - Data Flow

Test

## ☵ Kan (Water) - Error Handling

Test

## ☲ Li (Fire) - Observability

Test

## ☶ Gen (Mountain) - Boundary Constraints

Test

## ☱ Dui (Lake) - Success Path

Test</text>`);

      const planDir = dirname(draftPath);

      // planDir should be .sages/plans (the parent directory of the draft)
      expect(planDir).toBe(join(testProjectDir, ".sages", "plans"));

      // The buggy path would be: .sages/plans/test-project/.sages/plans
      const buggyPlanDir = join(planDir, "test-project", ".sages", "plans");
      expect(buggyPlanDir).not.toBe(planDir);

      // Verify we don't have nested .sages
      const planDirParts = planDir.split("/");
      const sagesCount = planDirParts.filter(p => p === ".sages").length;
      expect(sagesCount).toBe(1); // Only ONE .sages
    });

    it("should handle draft path with various naming patterns", () => {
      const testCases = [
        {
          draftPath: join(testProjectDir, ".sages", "plans", "simple.draft.md"),
          expectedPlanDir: join(testProjectDir, ".sages", "plans"),
          expectedPlanFile: join(testProjectDir, ".sages", "plans", "simple.plan.md"),
        },
        {
          draftPath: join(testProjectDir, ".sages", "plans", "my-project.draft.md"),
          expectedPlanDir: join(testProjectDir, ".sages", "plans"),
          expectedPlanFile: join(testProjectDir, ".sages", "plans", "my-project.plan.md"),
        },
        {
          draftPath: join(testProjectDir, ".sages", "plans", "test_project_123.draft.md"),
          expectedPlanDir: join(testProjectDir, ".sages", "plans"),
          expectedPlanFile: join(testProjectDir, ".sages", "plans", "test_project_123.plan.md"),
        },
      ];

      for (const tc of testCases) {
        const planDir = dirname(tc.draftPath);
        expect(planDir).toBe(tc.expectedPlanDir);

        // Verify no nested .sages in computed planDir
        const parts = planDir.split("/");
        const sagesCount = parts.filter(p => p === ".sages").length;
        expect(sagesCount).toBe(1);
      }
    });
  });
});