/**
 * Unit Tests for QiaoChui Tools
 * Tests review and decomposition logic
 */
import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { mkdirSync, rmSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";

// Helper to create temp project structure
function createTempProject(): string {
  const tempDir = join("/tmp", `qiaochui-test-${Date.now()}`);
  mkdirSync(tempDir, { recursive: true });
  mkdirSync(join(tempDir, ".sages", "plans"), { recursive: true });
  return tempDir;
}

// Helper to cleanup temp project
function cleanupTempProject(tempDir: string): void {
  rmSync(tempDir, { recursive: true, force: true });
}

// Mock the parseDraft function for testing
function parseDraftForTest(content: string): { sections: Record<string, string>; notes?: string } | null {
  try {
    const lines = content.split("\n");
    const sections: Record<string, string> = {};
    let currentSection = "";

    for (const line of lines) {
      if (line.startsWith("## ☰ Qian")) currentSection = "qian";
      else if (line.startsWith("## ☷ Kun")) currentSection = "kun";
      else if (line.startsWith("## ☳ Zhen")) currentSection = "zhen";
      else if (line.startsWith("## ☴ Xun")) currentSection = "xun";
      else if (line.startsWith("## ☵ Kan")) currentSection = "kan";
      else if (line.startsWith("## ☲ Li")) currentSection = "li";
      else if (line.startsWith("## ☶ Gen")) currentSection = "gen";
      else if (line.startsWith("## ☱ Dui")) currentSection = "dui";
      else if (line.startsWith("## Notes")) currentSection = "notes";
      else if (currentSection && line.trim()) {
        sections[currentSection] = (sections[currentSection] || "") + line + "\n";
      }
    }

    return { sections, notes: sections.notes };
  } catch {
    return null;
  }
}

function isDraftCompleteForTest(parsed: { sections: Record<string, string> } | null): boolean {
  if (!parsed) return false;
  const sectionCount = Object.values(parsed.sections).filter((s) => s && s.trim().length > 10).length;
  return sectionCount >= 5;
}

describe("QiaoChui Tools - Review Logic", () => {
  describe("Draft Completeness Check", () => {
    it("should approve complete draft (5+ sections filled)", () => {
      const content = `# Design Draft: test

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Build a web application with user authentication

## ☷ Kun (Earth) - Data Structures

- User: id, email, password_hash, created_at
- Session: id, user_id, token, expires_at

## ☳ Zhen (Thunder) - Trigger Mechanisms

- Login event creates session
- Logout event destroys session

## ☴ Xun (Wind) - Data Flow

Browser → API Gateway → Auth Service → Database

## ☵ Kan (Water) - Error Handling

- 401 for invalid credentials
- 500 for database errors with retry logic

## ☲ Li (Fire) - Observability

- Log all auth attempts to file
- Track metrics with timestamps

## ☶ Gen (Mountain) - Boundary Constraints

- Never log passwords
- Never expose tokens in URLs

## ☱ Dui (Lake) - Success Path

1. User POSTs credentials
2. System validates
3. Session created
4. Token returned in response</text>`;

      const parsed = parseDraftForTest(content);
      expect(isDraftCompleteForTest(parsed)).toBe(true);
    });

    it("should reject incomplete draft (less than 5 sections)", () => {
      const content = `# Design Draft: incomplete

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Build something

## ☷ Kun (Earth) - Data Structures

User entity</text>`;

      const parsed = parseDraftForTest(content);
      expect(isDraftCompleteForTest(parsed)).toBe(false);
    });

    it("should detect placeholder text", () => {
      const content = `# Design Draft: placeholder

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

TBD

## ☷ Kun (Earth) - Data Structures

TBD

## ☳ Zhen (Thunder) - Trigger Mechanisms

TBD

## ☴ Xun (Wind) - Data Flow

TBD

## ☵ Kan (Water) - Error Handling

TBD

## ☲ Li (Fire) - Observability

TBD</text>`;

      const parsed = parseDraftForTest(content);
      expect(isDraftCompleteForTest(parsed)).toBe(false);

      // Check for placeholders (TBD text)
      const hasPlaceholders = Object.values(parsed?.sections || {}).some(
        (s) => s && (s.includes("TBD") || s.includes("{")),
      );
      expect(hasPlaceholders).toBe(true);
    });
  });

  describe("Review Verdict Logic", () => {
    it("should return REVISE for incomplete draft", () => {
      const parsed = parseDraftForTest("# Design Draft: test\n\n## ☰ Qian\n\nabc");
      const isComplete = isDraftCompleteForTest(parsed);
      const verdict = isComplete ? "APPROVED" : "REVISE";
      expect(verdict).toBe("REVISE");
    });

    it("should return REVISE for draft with placeholders", () => {
      const content = `# Design Draft: test

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Build a system with proper security

## ☷ Kun (Earth) - Data Structures

User entity with fields

## ☳ Zhen (Thunder) - Trigger Mechanisms

Login creates session

## ☴ Xun (Wind) - Data Flow

Data flows through system

## ☵ Kan (Water) - Error Handling

Handle errors gracefully

## ☲ Li (Fire) - Observability

Log all operations

## ☶ Gen (Mountain) - Boundary Constraints

{Define boundaries}

## ☱ Dui (Lake) - Success Path

User logs in successfully</text>`;

      const parsed = parseDraftForTest(content);
      const hasPlaceholders = Object.values(parsed?.sections || {}).some(
        (s) => s && (s.includes("{") || s.includes("}")),
      );
      expect(hasPlaceholders).toBe(true);
    });

    it("should return APPROVED for complete draft without placeholders", () => {
      const content = `# Design Draft: test

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Build a secure authentication system

## ☷ Kun (Earth) - Data Structures

User: id, email, password_hash, created_at
Session: id, user_id, token, expires_at

## ☳ Zhen (Thunder) - Trigger Mechanisms

Login event creates session
Logout event destroys session
Token refresh extends session

## ☴ Xun (Wind) - Data Flow

Client → API → Auth Service → Database
Auth Service validates credentials
Database returns user record

## ☵ Kan (Water) - Error Handling

Invalid credentials return 401 Unauthorized
Database errors return 500 with exponential backoff
Network timeouts retry up to 3 times

## ☲ Li (Fire) - Observability

All auth attempts logged with timestamp
Session creation/destruction tracked
Failed login attempts alert security team

## ☶ Gen (Mountain) - Boundary Constraints

Never store plain text passwords
Never log sensitive credentials
Never expose tokens in URL parameters
Never allow cross-origin requests without CORS

## ☱ Dui (Lake) - Success Path

1. User submits email and password
2. System validates credentials against database
3. Session created with secure token
4. Token returned in HTTP-only cookie
5. User authenticated for subsequent requests</text>`;

      const parsed = parseDraftForTest(content);
      const isComplete = isDraftCompleteForTest(parsed);
      const hasPlaceholders = Object.values(parsed?.sections || {}).some(
        (s) => s && (s.includes("{") || s.includes("}")),
      );

      expect(isComplete).toBe(true);
      expect(hasPlaceholders).toBe(false);
    });
  });
});

describe("QiaoChui Tools - qiaochui_decompose Path Resolution", () => {
  // Import the actual tool
  const { qiaochui_decompose } = require("../../src/tools/qiaochui-tools");

  const testProjectDir = "/tmp/qiaochui-decompose-test";

  beforeEach(() => {
    // Create temp project directory with .sages/plans structure
    mkdirSync(join(testProjectDir, ".sages", "plans"), { recursive: true });
  });

  afterEach(() => {
    if (existsSync(testProjectDir)) {
      rmSync(testProjectDir, { recursive: true, force: true });
    }
  });

  describe("Plan file path resolution", () => {
    it("should create plan and execution files at same level as draft (using dirname)", () => {
      // This is the core test for the dirname() fix
      // Draft: .sages/plans/my-project.draft.md
      // Expected plan: .sages/plans/my-project.plan.md (NOT .sages/plans/my-project/.sages/plans/my-project.plan.md)

      const draftPath = join(testProjectDir, ".sages", "plans", "my-project.draft.md");
      const draftContent = `# Design Draft: my-project

Generated by: Fuxi
Timestamp: 2026-04-27T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Build a feature

## ☷ Kun (Earth) - Data Structures

Entity: id, name

## ☳ Zhen (Thunder) - Trigger Mechanisms

Action triggers event

## ☴ Xun (Wind) - Data Flow

Data flows here

## ☵ Kan (Water) - Error Handling

Handle errors

## ☲ Li (Fire) - Observability

Log operations

## ☶ Gen (Mountain) - Boundary Constraints

No constraints

## ☱ Dui (Lake) - Success Path

Success flow</text>`;

      writeFileSync(draftPath, draftContent);

      // Verify draft exists
      expect(existsSync(draftPath)).toBe(true);

      // Compute expected paths using dirname (the fix)
      const planDir = dirname(draftPath);
      const baseName = "my-project";
      const expectedPlanPath = join(planDir, `${baseName}.plan.md`);
      const expectedExecutionPath = join(planDir, `${baseName}.execution.yaml`);

      // The plan directory should be ".sages/plans" (parent of draft)
      expect(planDir).toBe(join(testProjectDir, ".sages", "plans"));

      // Plan file should be directly in .sages/plans, NOT in .sages/plans/my-project/.sages/plans/
      expect(expectedPlanPath).toBe(join(testProjectDir, ".sages", "plans", "my-project.plan.md"));

      // Verify there is NO nested .sages in the expected path
      const planPathParts = expectedPlanPath.split("/");
      const nestedSagesCount = planPathParts.filter(p => p === ".sages").length;
      expect(nestedSagesCount).toBe(1); // Only one .sages directory
    });

    it("should not create nested .sages/plans structure when using dirname", () => {
      // This test verifies the BUG is fixed: dirname(draft_path) gives correct parent
      // Bug would produce: .sages/plans/my-project/.sages/plans (WRONG)
      // Correct produces: .sages/plans (RIGHT)

      const draftPath = join(testProjectDir, ".sages", "plans", "test-project.draft.md");

      // Create a minimal draft
      writeFileSync(draftPath, `# Design Draft: test-project

Generated by: Fuxi
Timestamp: 2026-04-27T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Test

## ☷ Kun (Earth) - Data Structures

Test

## ☳ Zhen (Thunder) - Trigger Mechanisms

Test

## ☴ Xun (Wind) - Data Flow

Test

## ☵ Kan (Water) - Error Handling

Test

## ☲ Li (Fire) - Observability

Test

## ☶ Gen (Mountain) - Boundary Constraints

Test

## ☱ Dui (Lake) - Success Path

Test</text>`);

      const planDir = dirname(draftPath);

      // planDir should be .sages/plans (the parent directory of the draft)
      expect(planDir).toBe(join(testProjectDir, ".sages", "plans"));

      // The buggy path would be: .sages/plans/test-project/.sages/plans
      const buggyPlanDir = join(planDir, "test-project", ".sages", "plans");
      expect(buggyPlanDir).not.toBe(planDir);

      // Verify we don't have nested .sages
      const planDirParts = planDir.split("/");
      const sagesCount = planDirParts.filter(p => p === ".sages").length;
      expect(sagesCount).toBe(1); // Only ONE .sages
    });

    it("should handle draft path with various naming patterns", () => {
      const testCases = [
        {
          draftPath: join(testProjectDir, ".sages", "plans", "simple.draft.md"),
          expectedPlanDir: join(testProjectDir, ".sages", "plans"),
          expectedPlanFile: join(testProjectDir, ".sages", "plans", "simple.plan.md"),
        },
        {
          draftPath: join(testProjectDir, ".sages", "plans", "my-project.draft.md"),
          expectedPlanDir: join(testProjectDir, ".sages", "plans"),
          expectedPlanFile: join(testProjectDir, ".sages", "plans", "my-project.plan.md"),
        },
        {
          draftPath: join(testProjectDir, ".sages", "plans", "test_project_123.draft.md"),
          expectedPlanDir: join(testProjectDir, ".sages", "plans"),
          expectedPlanFile: join(testProjectDir, ".sages", "plans", "test_project_123.plan.md"),
        },
      ];

      for (const tc of testCases) {
        const planDir = dirname(tc.draftPath);
        expect(planDir).toBe(tc.expectedPlanDir);

        // Verify no nested .sages in computed planDir
        const parts = planDir.split("/");
        const sagesCount = parts.filter(p => p === ".sages").length;
        expect(sagesCount).toBe(1);
      }
    });
  });
});