/**
 * Unit Tests for parseDraft utilities
 * Tests draft parsing and completeness validation
 */
import { describe, it, expect } from "bun:test";
import { parseDraft, isDraftComplete, type ParsedDraft } from "../../src/utils/parseDraft";

describe("parseDraft", () => {
  it("should parse a complete draft with all 8 trigrams", () => {
    const content = `# Design Draft: test-project

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Build a user authentication system

## ☷ Kun (Earth) - Data Structures

- User entity with id, email, password
- Session entity with token and expiry

## ☳ Zhen (Thunder) - Trigger Mechanisms

- User login event triggers session creation
- Logout event triggers session deletion

## ☴ Xun (Wind) - Data Flow

User → API → Auth Service → Database

## ☵ Kan (Water) - Error Handling

- Invalid credentials return 401
- Database errors return 500 with retry

## ☲ Li (Fire) - Observability

- Log all authentication attempts
- Track session creation/deletion metrics

## ☶ Gen (Mountain) - Boundary Constraints

- Do not store passwords in plain text
- Do not allow session tokens in URL parameters

## ☱ Dui (Lake) - Success Path

1. User submits credentials
2. System validates against database
3. Session created and token returned
4. User authenticated for subsequent requests

## Notes

This is a test implementation`;

    const result = parseDraft(content);

    expect(result).not.toBeNull();
    expect(result!.name).toBe("test-project");
    expect(result!.timestamp).toBe("2026-04-26T10:00:00.000Z");
    expect(result!.status).toBe("draft");
    expect(result!.sections.qian).toContain("Build a user authentication system");
    expect(result!.sections.kun).toContain("User entity");
    expect(result!.sections.dui).toContain("User submits credentials");
    expect(result!.notes).toBe("This is a test implementation");
  });

  it("should parse draft with only some sections filled", () => {
    const content = `# Design Draft: partial

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Simple task

## ☷ Kun (Earth) - Data Structures

{Define core entities}

## ☴ Xun (Wind) - Data Flow

{Define how data flows}

## Notes

Needs more work`;

    const result = parseDraft(content);

    expect(result).not.toBeNull();
    expect(result!.name).toBe("partial");
    expect(result!.sections.qian).toContain("Simple task");
    expect(result!.sections.kun).toContain("{Define core entities}");
  });

  it("should return draft with empty fields for unrecognized format", () => {
    const result = parseDraft("not a valid draft");
    expect(result).not.toBeNull();
    expect(result!.name).toBe("");
  });

  it("should handle empty content", () => {
    const result = parseDraft("");
    expect(result).not.toBeNull();
    expect(result!.sections).toEqual({});
  });

  it("should parse sections with emoji headers", () => {
    const content = `# Design Draft: emoji-test

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Test content`;

    const result = parseDraft(content);

    expect(result).not.toBeNull();
    expect(result!.sections.qian).toBe("Test content\n");
  });

  it("should handle content without Notes section", () => {
    const content = `# Design Draft: no-notes

Generated by: Fuxi
Timestamp: 2026-04-26T10:00:00.000Z
Status: draft

## ☰ Qian (Heaven) - Core Intent

Only qian section

## ☷ Kun (Earth) - Data Structures

Some data`;

    const result = parseDraft(content);

    expect(result).not.toBeNull();
    expect(result!.name).toBe("no-notes");
    expect(result!.notes).toBe("");
  });

  it("should skip Generated by line", () => {
    const content = `# Design Draft: skip-test

Generated by: Custom Agent
Timestamp: 2026-04-26T10:00:00.000Z
Status: review

## ☰ Qian (Heaven) - Core Intent

Content here`;

    const result = parseDraft(content);

    expect(result).not.toBeNull();
    expect(result!.name).toBe("skip-test");
  });
});

describe("isDraftComplete", () => {
  it("should return true for drafts with 5+ filled sections", () => {
    const draft: ParsedDraft = {
      name: "test",
      timestamp: "2026-04-26T10:00:00.000Z",
      status: "draft",
      sections: {
        qian: "Core intent content here",
        kun: "Data structures content here",
        zhen: "Triggers content here",
        xun: "Data flow content here",
        kan: "Error handling content here",
      },
    };

    expect(isDraftComplete(draft)).toBe(true);
  });

  it("should return false for drafts with less than 5 filled sections", () => {
    const draft: ParsedDraft = {
      name: "test",
      timestamp: "2026-04-26T10:00:00.000Z",
      status: "draft",
      sections: {
        qian: "Core intent content here",
        kun: "Data structures content here",
      },
    };

    expect(isDraftComplete(draft)).toBe(false);
  });

  it("should return false for empty sections", () => {
    const draft: ParsedDraft = {
      name: "test",
      timestamp: "2026-04-26T10:00:00.000Z",
      status: "draft",
      sections: {
        qian: "",
        kun: "Data structures",
      },
    };

    expect(isDraftComplete(draft)).toBe(false);
  });

  it("should return false for sections with placeholder text", () => {
    const draft: ParsedDraft = {
      name: "test",
      timestamp: "2026-04-26T10:00:00.000Z",
      status: "draft",
      sections: {
        qian: "{Define core intent}",
        kun: "Data structures",
        zhen: "Triggers",
        xun: "Data flow",
        kan: "Error handling",
      },
    };

    // Placeholder text is only 16 chars, threshold is 10
    expect(isDraftComplete(draft)).toBe(false);
  });

  it("should return false for sections with exactly 10 chars", () => {
    const draft: ParsedDraft = {
      name: "test",
      timestamp: "2026-04-26T10:00:00.000Z",
      status: "draft",
      sections: {
        qian: "1234567890", // exactly 10 chars
        kun: "Data structures",
        zhen: "Triggers",
        xun: "Data flow",
        kan: "Error handling",
      },
    };

    // 10 chars is NOT > 10, so qian doesn't count
    expect(isDraftComplete(draft)).toBe(false);
  });

  it("should return false for empty sections object", () => {
    const draft: ParsedDraft = {
      name: "test",
      timestamp: "2026-04-26T10:00:00.000Z",
      status: "draft",
      sections: {},
    };

    expect(isDraftComplete(draft)).toBe(false);
  });

  it("should count sections with more than 10 chars after trim", () => {
    const draft: ParsedDraft = {
      name: "test",
      timestamp: "2026-04-26T10:00:00.000Z",
      status: "draft",
      sections: {
        qian: "12345678901", // 11 chars
        kun: "database schema", // 15 chars
        zhen: "also short too", // 14 chars
        xun: "long enough here", // 15 chars
        kan: "Error handling content here", // 26 chars
      },
    };

    expect(isDraftComplete(draft)).toBe(true);
  });
});