/**
 * QiaoChui Tools (巧倕) - Technical Expert 
 * 
 * Modularized structure:
 * - index.ts: Tool registration (this file)
 * - review-service.ts: MDD plane review logic
 * - decompose-service.ts: Task decomposition logic
 * - types.ts: Shared type definitions
 */

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { Type } from "typebox";
import { join } from "node:path";
import { existsSync, readFileSync } from "node:fs";
import { FileService } from "../../services/file-service.js";
import { performDeepReview, generateDeepFeasibilityReport } from "./review-service.js";
import { generateMDDTasks, resolveFileConflicts } from "./decompose-service.js";
import { getUserDefaultModel } from "../../utils/model-helper.js";
import type { MDDTask } from "./types.js";

const WORKSPACE_DIR = ".sages/workspace";

/**
 * Validate that review was completed and score > 80
 */
function validateReviewPrerequisite(cwd: string): { valid: boolean; score: number; message?: string } {
  const statePath = join(cwd, WORKSPACE_DIR, "state.json");

  if (!existsSync(statePath)) {
    return { valid: false, score: 0, message: "No workflow state found. Run qiaochui_review first." };
  }

  try {
    const content = readFileSync(statePath, "utf-8");
    const state = JSON.parse(content);

    if (typeof state.score !== "number") {
      return { valid: false, score: 0, message: "No review score found. Run qiaochui_review first." };
    }

    if (state.score < 80) {
      return { valid: false, score: state.score, message: `Score ${state.score} is below 80. Review must be approved (score >= 80) before decomposition.` };
    }

    return { valid: true, score: state.score };
  } catch {
    return { valid: false, score: 0, message: "Failed to read workflow state." };
  }
}

// Helper functions for decomposition
function buildPlanMarkdown(planName: string, tasks: MDDTask[]): string {
  let markdown = `# Task Plan

Generated by: QiaoChui (巧倕) - Technical Expert
Timestamp: ${new Date().toISOString()}
Plan: ${planName}

## MDD Task Breakdown

| ID | Description | Plane | Priority | Dependencies |
|----|-------------|-------|----------|--------------|
`;

  for (const task of tasks) {
    markdown += `| ${task.id} | ${task.description} | ${task.plane} | ${task.priority} | ${task.dependsOn.join(", ") || "-"} |\n`;
  }

  markdown += `\n## Task Details\n\n`;
  for (const task of tasks) {
    markdown += `### ${task.id}: ${task.description}\n`;
    markdown += `- **Plane**: ${task.plane}\n`;
    markdown += `- **Priority**: ${task.priority}\n`;
    if (task.dependsOn.length > 0) markdown += `- **Depends on**: ${task.dependsOn.join(", ")}\n`;
    if (task.files?.length) markdown += `- **Files**: ${task.files.join(", ")}\n`;
    markdown += "\n";
  }

  markdown += `## Total Estimated Time: ${tasks.length * 10} minutes\n`;
  return markdown;
}

function buildExecutionYaml(planName: string, tasks: MDDTask[], maxParallel: number, useSubagent: boolean): string {
  return `# Execution Plan
# Generated by QiaoChui (巧倕) - Technical Expert
# Plan: ${planName}
# Created: ${new Date().toISOString()}

name: ${planName}

settings:
  maxParallel: ${maxParallel}
  useSubagent: ${useSubagent}
  maxRetry: 1
  autoCommit: true
  subagentConfig:
    skills:
      - luban
    maxContext: 4000
    timeout: 300

tasks:
${tasks.map((t) => `  - id: ${t.id}
    description: "${t.description}"
    plane: ${t.plane}
    priority: ${t.priority === "high" ? 1 : t.priority === "medium" ? 2 : 3}
    dependsOn: [${t.dependsOn.map(d => `"${d}"`).join(", ")}]
    files: [${(t.files || []).map(f => `"${f}"`).join(", ")}]`).join("\n")}`;
}

/**
 * Extract plan name from draft content
 */
function extractPlanName(content: string): string | null {
  const match = content.match(/^#\s*System Design:\s*(.+)$/m);
  return match ? match[1].trim() : null;
}

export function registerQiaoChuiTools(pi: ExtensionAPI): void {
  /**
   * qiaochui_review - Review draft for technical feasibility
   * Review Mode (Read-Only): Only read draft.md
   *
   * Two modes:
   *   - Without observation: returns heuristic hints + semantic-tool guidance.
   *     The LLM reads the draft using serena_read_file / graphify_query,
   *     computes a score against the 5 dimensions, and re-calls with observation.
   *   - With observation {score, notes?}: validates the score, computes verdict,
   *     persists state.score to state.json. Returns verdict + can_start_plan.
   *
   * Score thresholds: >=80 APPROVED, 50-79 REVISE, <50 REJECTED
   */
  pi.registerTool({
    name: "qiaochui_review",
    label: "Review Draft",
    description: "Review draft for technical feasibility. Without observation: returns heuristic hints + semantic-tool guidance for the LLM to score the draft. With observation {score, notes?}: persists score to state.json and returns verdict (APPROVED/REVISE/REJECTED). Threshold: >=80 APPROVED. Replaces the old qiaochui_review + fuxi_update_score two-step.",
    parameters: Type.Object({
      draft_path: Type.Optional(Type.String({ description: "Path to draft.md (default: .sages/workspace/draft.md)" })),
      observation: Type.Optional(Type.Object({
        score: Type.Number({ description: "LLM-assessed score (0-100)" }),
        notes: Type.Optional(Type.String({ description: "Optional review notes" })),
      }, { description: "Score observation (LLM's final assessment)" })),
    }),
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const cwd = ctx.cwd;
      const fileService = new FileService(cwd);
      const draft_filename = params.draft_path ? params.draft_path.replace(`${WORKSPACE_DIR}/`, "") : "draft.md";

      try {
        // Validate path to prevent traversal
        if (!fileService.validatePath(draft_filename)) {
          return {
            content: [{ type: "text", text: JSON.stringify({
              status: "error",
              error: `Invalid path: ${draft_filename}`,
            }) }],
            isError: true,
            details: { draft_filename },
          };
        }

        const content = fileService.read(draft_filename);
        if (!content) {
          return {
            content: [{ type: "text", text: JSON.stringify({
              status: "error",
              error: `Draft not found: ${draft_filename}`,
            }) }],
            isError: true,
            details: { draft_filename },
          };
        }

        // ── Observation path: validate + persist score ─────────────────
        if (params.observation) {
          const score = params.observation.score;
          if (typeof score !== "number" || score < 0 || score > 100) {
            return {
              content: [{ type: "text", text: JSON.stringify({
                status: "error",
                error: `Score must be a number in range 0-100, got: ${params.observation.score}`,
              }) }],
              isError: true,
              details: { score: params.observation.score },
            };
          }

          let verdict: "APPROVED" | "REVISE" | "REJECTED";
          if (score >= 80) verdict = "APPROVED";
          else if (score >= 50) verdict = "REVISE";
          else verdict = "REJECTED";

          // Persist to state.json via FileService.
          const existing = fileService.readJson<Record<string, unknown>>("state.json") || {};
          existing.score = score;
          if (params.observation.notes) existing.reviewNotes = params.observation.notes;
          fileService.writeJson("state.json", existing);

          return {
            content: [{ type: "text", text: JSON.stringify({
              status: "complete",
              score,
              verdict,
              can_start_plan: score >= 80,
              state_persisted: true,
              summary: `Review complete: ${verdict} (${score}). Plan can start: ${score > 80}.`,
            }) }],
            details: { score, verdict, persisted_to: "state.json" },
          };
        }

        // ── No observation: return heuristic hints + guidance ──────────
        const deepResult = performDeepReview(content);
        const feasibilityReport = generateDeepFeasibilityReport(deepResult);

        return {
          content: [{
            type: "text",
            text: JSON.stringify({
              status: "in_progress",
              intent: "Read draft.md using semantic tools (serena_read_file, graphify_query) to assess the 5 dimensions below. Then call qiaochui_review with observation {score, notes?} to persist the score.",
              validation: {
                dimensions: [
                  { name: "completeness", weight: 25, description: "All 7 MDD planes covered?" },
                  { name: "clarity", weight: 20, description: "Writing clear? Examples concrete?" },
                  { name: "feasibility", weight: 25, description: "Technical approach implementable? Dependencies clear?" },
                  { name: "testability", weight: 15, description: "Success path defined? Error handling concrete?" },
                  { name: "boundaries", weight: 15, description: "Out-of-scope clear? Limits stated?" },
                ],
                pass_threshold: 80,
                draft_path: draft_filename,
              },
              heuristic_hints: {
                heuristic_score: deepResult.score,
                heuristic_verdict: deepResult.overallStatus,
                plane_count: deepResult.planeAssessments.length,
                blockers: deepResult.blockers.length,
                top_recommendations: deepResult.recommendations.slice(0, 5),
              },
            }),
          }],
          details: { draft_filename, deep_result: deepResult, feasibilityReport },
        };
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: JSON.stringify({ status: "error", error: msg }) }],
          isError: true,
          details: { error: msg },
        };
      }
    },
  });

  /**
   * qiaochui_decompose - Decompose approved design into tasks
   * Prerequisites: qiaochui_review completed, score > 80
   * Creates: plan.md (task descriptions), execution.yaml (task config with dependencies)
   */
  pi.registerTool({
    name: "qiaochui_decompose",
    label: "Decompose",
    description: "Decompose design into tasks. Creates plan.md and execution.yaml with MDD plane classification, priorities, dependencies.",
    parameters: Type.Object({
      draft_path: Type.Optional(Type.String({ description: "Path to draft.md (default: .sages/workspace/draft.md)" })),
      max_tasks: Type.Optional(Type.Number({ description: "Maximum number of tasks to generate (default: 10, max: 20)" })),
      use_subagent: Type.Optional(Type.Boolean({ description: "Use isolated subagent mode for parallel execution (default: true)" })),
      max_parallel: Type.Optional(Type.Number({ description: "Maximum parallel subagents (default: 3)" })),
    }),
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const cwd = ctx.cwd;
      const fileService = new FileService(cwd);
      const draft_filename = params.draft_path ? params.draft_path.replace(`${WORKSPACE_DIR}/`, "") : "draft.md";
      const max_tasks = params.max_tasks || 10;
      const use_subagent = params.use_subagent !== false;
      const max_parallel = params.max_parallel || 3;

      try {
        // Validate path to prevent traversal
        if (!fileService.validatePath(draft_filename)) {
          return {
            content: [{ type: "text", text: JSON.stringify({
              status: "error",
              error: `Invalid path: ${draft_filename}`,
            }) }],
            isError: true,
            details: { draft_filename },
          };
        }

        // Validate review prerequisite: score must be >= 80
        const reviewValidation = validateReviewPrerequisite(cwd);
        if (!reviewValidation.valid) {
          return {
            content: [{ type: "text", text: JSON.stringify({
              status: "error",
              error: reviewValidation.message || "Review prerequisite failed",
            }) }],
            isError: true,
            details: { score: reviewValidation.score },
          };
        }

        // Read draft content
        const content = fileService.read(draft_filename);

        if (!content) {
          return {
            content: [{ type: "text", text: JSON.stringify({ success: false, error: { message: `Draft not found: ${draft_filename}` } }) }],
            isError: true,
            details: { draft_filename },
          };
        }

        const workspacePath = fileService.getWorkspacePath();

        // Extract plan name from draft
        const planName = extractPlanName(content) || "workflow";
        
        // Generate tasks with MDD plane classification
        const tasks = generateMDDTasks(content, max_tasks);

        // Resolve file conflicts - tasks editing the same file become sequential
        const tasksWithResolvedConflicts = resolveFileConflicts(tasks);

        // Build plan markdown
        let planMarkdown = `# Task Plan

Generated by: QiaoChui (巧倕) - Technical Expert
Timestamp: ${new Date().toISOString()}
Plan: ${planName}

## MDD Task Breakdown

| ID | Description | Plane | Priority | Dependencies |
|----|-------------|-------|----------|--------------|
`;
        for (const task of tasksWithResolvedConflicts) {
          planMarkdown += `| ${task.id} | ${task.description} | ${task.plane} | ${task.priority} | ${task.dependsOn.join(", ") || "-"} |\n`;
        }

        planMarkdown += `\n## Task Details\n\n`;
        for (const task of tasksWithResolvedConflicts) {
          planMarkdown += `### ${task.id}: ${task.description}\n`;
          planMarkdown += `- **Plane**: ${task.plane}\n`;
          planMarkdown += `- **Priority**: ${task.priority}\n`;
          if (task.dependsOn.length > 0) {
            planMarkdown += `- **Depends on**: ${task.dependsOn.join(", ")}\n`;
          }
          if (task.files && task.files.length > 0) {
            planMarkdown += `- **Files**: ${task.files.join(", ")}\n`;
          }
          planMarkdown += "\n";
        }

        const totalTime = tasksWithResolvedConflicts.length * 10;
        planMarkdown += `## Total Estimated Time: ${totalTime} minutes\n`;

        // Build execution YAML (model will be set by SubagentExecutor from user settings)
        const executionYaml = `# Execution Plan
# Generated by QiaoChui (巧倕) - Technical Expert
# Plan: ${planName}
# Created: ${new Date().toISOString()}

name: ${planName}

settings:
  maxParallel: ${max_parallel}
  useSubagent: ${use_subagent}
  maxRetry: 1
  autoCommit: true
  subagentConfig:
    skills:
      - luban
    maxContext: 4000
    timeout: 300

tasks:
${tasksWithResolvedConflicts.map((t) => `  - id: ${t.id}
    description: "${t.description}"
    plane: ${t.plane}
    priority: ${t.priority === "high" ? 1 : t.priority === "medium" ? 2 : 3}
    dependsOn: [${t.dependsOn.map(d => `"${d}"`).join(", ")}]
    files: [${(t.files || []).map(f => `"${f}"`).join(", ")}]`).join("\n")}
`;

        const planPath = "plan.md";
        const executionPath = "execution.yaml";

        fileService.write(planPath, planMarkdown);
        fileService.write(executionPath, executionYaml);

        return {
          content: [{
            type: "text",
            text: JSON.stringify({
              success: true,
              plan_name: planName,
              plan_path: join(workspacePath, planPath),
              execution_path: join(workspacePath, executionPath),
              task_count: tasksWithResolvedConflicts.length,
              estimated_time: totalTime,
              planes: [...new Set(tasksWithResolvedConflicts.map(t => t.plane))],
              execution_mode: {
                use_subagent: use_subagent,
                max_parallel: max_parallel,
                description: use_subagent
                  ? "Isolated subagent mode - each task runs in a separate pi process"
                  : "Shared context mode - all tasks share the same context",
              },
              workspace: workspacePath,
              note: "Tasks stored in execution.yaml (not tasks.json)",
            }),
          }],
          details: { planName, planPath: join(workspacePath, planPath), executionPath: join(workspacePath, executionPath), taskCount: tasksWithResolvedConflicts.length, useSubagent: use_subagent, maxParallel: max_parallel },
        };
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        return {
          content: [{ type: "text", text: JSON.stringify({ success: false, error: { message: msg } }) }],
          isError: true,
          details: { error: msg },
        };
      }
    },
  });
}
